// Generated from /Users/vishnukummariguntla/Downloads/ipl_2026_player_salaries_bidders.xlsx
// Values are in crore rupees and anchor the auction bot market.
export const auctionSalaryAnchors = {
  "AM Ghazanfar": {"salaryCr": 4.8, "team": "Mumbai Indians", "bidder": "Mumbai Indians", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Abdul Samad": {"salaryCr": 4.2, "team": "Lucknow Super Giants", "bidder": "Lucknow Super Giants", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Abhinandan Singh": {"salaryCr": 0.3, "team": "Royal Challengers Bengaluru", "bidder": "Royal Challengers Bengaluru", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Abhishek Sharma": {"salaryCr": 14.0, "team": "Sunrisers Hyderabad", "bidder": "Sunrisers Hyderabad", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Abishek Porel": {"salaryCr": 4.0, "team": "Delhi Capitals", "bidder": "Delhi Capitals", "role": "Wicket-Keeper", "status": "Current squad salary / retained or acquired by franchise"},
  "Aiden Markram": {"salaryCr": 2.0, "team": "Lucknow Super Giants", "bidder": "Lucknow Super Giants", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Ajay Mandal": {"salaryCr": 0.3, "team": "Delhi Capitals", "bidder": "Delhi Capitals", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Ajinkya Rahane": {"salaryCr": 1.5, "team": "Kolkata Knight Riders", "bidder": "Kolkata Knight Riders", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Akash Singh": {"salaryCr": 0.3, "team": "Lucknow Super Giants", "bidder": "Lucknow Super Giants", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Angkrish Raghuvanshi": {"salaryCr": 3.0, "team": "Kolkata Knight Riders", "bidder": "Kolkata Knight Riders", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Aniket Verma": {"salaryCr": 0.3, "team": "Sunrisers Hyderabad", "bidder": "Sunrisers Hyderabad", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Anshul Kamboj": {"salaryCr": 3.4, "team": "Chennai Super Kings", "bidder": "Chennai Super Kings", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Anuj Rawat": {"salaryCr": 0.3, "team": "Gujarat Titans", "bidder": "Gujarat Titans", "role": "Wicket-Keeper", "status": "Current squad salary / retained or acquired by franchise"},
  "Anukul Roy": {"salaryCr": 0.4, "team": "Kolkata Knight Riders", "bidder": "Kolkata Knight Riders", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Aquib Nabi": {"salaryCr": 8.4, "team": "Delhi Capitals", "bidder": "Delhi Capitals", "role": "All-Rounder", "status": "2026 auction sold player (verified top-buy listing)"},
  "Arshad Khan": {"salaryCr": 1.3, "team": "Gujarat Titans", "bidder": "Gujarat Titans", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Arshdeep Singh": {"salaryCr": 18.0, "team": "Punjab Kings", "bidder": "Punjab Kings", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Arshin Kulkarni": {"salaryCr": 0.3, "team": "Lucknow Super Giants", "bidder": "Lucknow Super Giants", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Ashutosh Sharma": {"salaryCr": 3.8, "team": "Delhi Capitals", "bidder": "Delhi Capitals", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Ashwani Kumar": {"salaryCr": 0.3, "team": "Mumbai Indians", "bidder": "Mumbai Indians", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Avesh Khan": {"salaryCr": 9.75, "team": "Lucknow Super Giants", "bidder": "Lucknow Super Giants", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Axar Patel": {"salaryCr": 16.5, "team": "Delhi Capitals", "bidder": "Delhi Capitals", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Ayush Badoni": {"salaryCr": 4.0, "team": "Lucknow Super Giants", "bidder": "Lucknow Super Giants", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Ayush Mhatre": {"salaryCr": 0.3, "team": "Chennai Super Kings", "bidder": "Chennai Super Kings", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Azmatullah Omarzai": {"salaryCr": 2.4, "team": "Punjab Kings", "bidder": "Punjab Kings", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Bhuvneshwar Kumar": {"salaryCr": 10.75, "team": "Royal Challengers Bengaluru", "bidder": "Royal Challengers Bengaluru", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Brydon Carse": {"salaryCr": 1.0, "team": "Sunrisers Hyderabad", "bidder": "Sunrisers Hyderabad", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Cameron Green": {"salaryCr": 25.2, "team": "Kolkata Knight Riders", "bidder": "Kolkata Knight Riders", "role": "All-Rounder", "status": "2026 auction sold player (verified top-buy listing)"},
  "Corbin Bosch": {"salaryCr": 0.75, "team": "Mumbai Indians", "bidder": "Mumbai Indians", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Deepak Chahar": {"salaryCr": 9.25, "team": "Mumbai Indians", "bidder": "Mumbai Indians", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Devdutt Padikkal": {"salaryCr": 2.0, "team": "Royal Challengers Bengaluru", "bidder": "Royal Challengers Bengaluru", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Dewald Brevis": {"salaryCr": 2.2, "team": "Chennai Super Kings", "bidder": "Chennai Super Kings", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Dhruv Jurel": {"salaryCr": 14.0, "team": "Rajasthan Royals", "bidder": "Rajasthan Royals", "role": "Wicket-Keeper", "status": "Current squad salary / retained or acquired by franchise"},
  "Digvesh Singh": {"salaryCr": 0.3, "team": "Lucknow Super Giants", "bidder": "Lucknow Super Giants", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Dushmantha Chameera": {"salaryCr": 0.75, "team": "Delhi Capitals", "bidder": "Delhi Capitals", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Eshan Malinga": {"salaryCr": 1.2, "team": "Sunrisers Hyderabad", "bidder": "Sunrisers Hyderabad", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Glenn Phillips": {"salaryCr": 2.0, "team": "Gujarat Titans", "bidder": "Gujarat Titans", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Gurjapneet Singh": {"salaryCr": 2.2, "team": "Chennai Super Kings", "bidder": "Chennai Super Kings", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Gurnoor Brar": {"salaryCr": 1.3, "team": "Gujarat Titans", "bidder": "Gujarat Titans", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Hardik Pandya": {"salaryCr": 16.35, "team": "Mumbai Indians", "bidder": "Mumbai Indians", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Harnoor Singh": {"salaryCr": 0.3, "team": "Punjab Kings", "bidder": "Punjab Kings", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Harpreet Brar": {"salaryCr": 1.5, "team": "Punjab Kings", "bidder": "Punjab Kings", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Harsh Dubey": {"salaryCr": 0.3, "team": "Sunrisers Hyderabad", "bidder": "Sunrisers Hyderabad", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Harshal Patel": {"salaryCr": 8.0, "team": "Sunrisers Hyderabad", "bidder": "Sunrisers Hyderabad", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Harshit Rana": {"salaryCr": 4.0, "team": "Kolkata Knight Riders", "bidder": "Kolkata Knight Riders", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Heinrich Klaasen": {"salaryCr": 23.0, "team": "Sunrisers Hyderabad", "bidder": "Sunrisers Hyderabad", "role": "Wicket-Keeper", "status": "Current squad salary / retained or acquired by franchise"},
  "Himmat Singh": {"salaryCr": 0.3, "team": "Lucknow Super Giants", "bidder": "Lucknow Super Giants", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Ishan Kishan": {"salaryCr": 11.25, "team": "Sunrisers Hyderabad", "bidder": "Sunrisers Hyderabad", "role": "Wicket-Keeper", "status": "Current squad salary / retained or acquired by franchise"},
  "Ishant Sharma": {"salaryCr": 0.75, "team": "Gujarat Titans", "bidder": "Gujarat Titans", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Jacob Bethell": {"salaryCr": 2.6, "team": "Royal Challengers Bengaluru", "bidder": "Royal Challengers Bengaluru", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Jamie Overton": {"salaryCr": 1.5, "team": "Chennai Super Kings", "bidder": "Chennai Super Kings", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Jasprit Bumrah": {"salaryCr": 18.0, "team": "Mumbai Indians", "bidder": "Mumbai Indians", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Jayant Yadav": {"salaryCr": 0.75, "team": "Gujarat Titans", "bidder": "Gujarat Titans", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Jaydev Unadkat": {"salaryCr": 1.0, "team": "Sunrisers Hyderabad", "bidder": "Sunrisers Hyderabad", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Jitesh Sharma": {"salaryCr": 11.0, "team": "Royal Challengers Bengaluru", "bidder": "Royal Challengers Bengaluru", "role": "Wicket-Keeper", "status": "Current squad salary / retained or acquired by franchise"},
  "Jofra Archer": {"salaryCr": 12.5, "team": "Rajasthan Royals", "bidder": "Rajasthan Royals", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Jos Buttler": {"salaryCr": 15.75, "team": "Gujarat Titans", "bidder": "Gujarat Titans", "role": "Wicket-Keeper", "status": "Current squad salary / retained or acquired by franchise"},
  "Josh Hazlewood": {"salaryCr": 12.5, "team": "Royal Challengers Bengaluru", "bidder": "Royal Challengers Bengaluru", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Josh Inglis": {"salaryCr": 8.6, "team": "Lucknow Super Giants", "bidder": "Lucknow Super Giants", "role": "Wicket-Keeper", "status": "2026 auction sold player (verified top-buy listing)"},
  "KL Rahul": {"salaryCr": 14.0, "team": "Delhi Capitals", "bidder": "Delhi Capitals", "role": "Wicket-Keeper", "status": "Current squad salary / retained or acquired by franchise"},
  "Kagiso Rabada": {"salaryCr": 10.75, "team": "Gujarat Titans", "bidder": "Gujarat Titans", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Kamindu Mendis": {"salaryCr": 0.75, "team": "Sunrisers Hyderabad", "bidder": "Sunrisers Hyderabad", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Kartik Sharma": {"salaryCr": 14.2, "team": "Chennai Super Kings", "bidder": "Chennai Super Kings", "role": "Batter", "status": "2026 auction sold player (verified top-buy listing)"},
  "Karun Nair": {"salaryCr": 0.5, "team": "Delhi Capitals", "bidder": "Delhi Capitals", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Khaleel Ahmed": {"salaryCr": 4.8, "team": "Chennai Super Kings", "bidder": "Chennai Super Kings", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Krunal Pandya": {"salaryCr": 5.75, "team": "Royal Challengers Bengaluru", "bidder": "Royal Challengers Bengaluru", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Kuldeep Yadav": {"salaryCr": 13.25, "team": "Delhi Capitals", "bidder": "Delhi Capitals", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Kumar Kushagra": {"salaryCr": 0.65, "team": "Gujarat Titans", "bidder": "Gujarat Titans", "role": "Wicket-Keeper", "status": "Current squad salary / retained or acquired by franchise"},
  "Kwena Maphaka": {"salaryCr": 1.5, "team": "Rajasthan Royals", "bidder": "Rajasthan Royals", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Lhuan-dre Pretorius": {"salaryCr": 0.3, "team": "Rajasthan Royals", "bidder": "Rajasthan Royals", "role": "Wicket-Keeper", "status": "Current squad salary / retained or acquired by franchise"},
  "Liam Livingstone": {"salaryCr": 13.0, "team": "Sunrisers Hyderabad", "bidder": "Sunrisers Hyderabad", "role": "All-Rounder", "status": "2026 auction sold player (verified top-buy listing)"},
  "Lockie Ferguson": {"salaryCr": 2.0, "team": "Punjab Kings", "bidder": "Punjab Kings", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "M Siddharth": {"salaryCr": 0.75, "team": "Lucknow Super Giants", "bidder": "Lucknow Super Giants", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "MS Dhoni": {"salaryCr": 4.0, "team": "Chennai Super Kings", "bidder": "Chennai Super Kings", "role": "Wicket-Keeper", "status": "Current squad salary / retained or acquired by franchise"},
  "Madhav Tiwari": {"salaryCr": 0.4, "team": "Delhi Capitals", "bidder": "Delhi Capitals", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Manav Suthar": {"salaryCr": 0.3, "team": "Gujarat Titans", "bidder": "Gujarat Titans", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Manish Pandey": {"salaryCr": 0.75, "team": "Kolkata Knight Riders", "bidder": "Kolkata Knight Riders", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Marco Jansen": {"salaryCr": 7.0, "team": "Punjab Kings", "bidder": "Punjab Kings", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Marcus Stoinis": {"salaryCr": 11.0, "team": "Punjab Kings", "bidder": "Punjab Kings", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Matheesha Pathirana": {"salaryCr": 18.0, "team": "Kolkata Knight Riders", "bidder": "Kolkata Knight Riders", "role": "Bowler", "status": "2026 auction sold player (verified top-buy listing)"},
  "Matthew Breetzke": {"salaryCr": 0.75, "team": "Lucknow Super Giants", "bidder": "Lucknow Super Giants", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Mayank Yadav": {"salaryCr": 11.0, "team": "Lucknow Super Giants", "bidder": "Lucknow Super Giants", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Mitchell Marsh": {"salaryCr": 3.4, "team": "Lucknow Super Giants", "bidder": "Lucknow Super Giants", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Mitchell Owen": {"salaryCr": 3.0, "team": "Punjab Kings", "bidder": "Punjab Kings", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Mitchell Santner": {"salaryCr": 2.0, "team": "Mumbai Indians", "bidder": "Mumbai Indians", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Mitchell Starc": {"salaryCr": 11.75, "team": "Delhi Capitals", "bidder": "Delhi Capitals", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Mohammed Siraj": {"salaryCr": 12.25, "team": "Gujarat Titans", "bidder": "Gujarat Titans", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Mohsin Khan": {"salaryCr": 4.0, "team": "Lucknow Super Giants", "bidder": "Lucknow Super Giants", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Mukesh Choudhary": {"salaryCr": 0.3, "team": "Chennai Super Kings", "bidder": "Chennai Super Kings", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Mukesh Kumar": {"salaryCr": 8.0, "team": "Delhi Capitals", "bidder": "Delhi Capitals", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Musheer Khan": {"salaryCr": 0.3, "team": "Punjab Kings", "bidder": "Punjab Kings", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Mustafizur Rahman": {"salaryCr": 9.2, "team": "Kolkata Knight Riders", "bidder": "Kolkata Knight Riders", "role": "Bowler", "status": "2026 auction sold player (verified top-buy listing)"},
  "Naman Dhir": {"salaryCr": 5.25, "team": "Mumbai Indians", "bidder": "Mumbai Indians", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Nandre Burger": {"salaryCr": 3.5, "team": "Rajasthan Royals", "bidder": "Rajasthan Royals", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Nathan Ellis": {"salaryCr": 2.0, "team": "Chennai Super Kings", "bidder": "Chennai Super Kings", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Nehal Wadhera": {"salaryCr": 4.2, "team": "Punjab Kings", "bidder": "Punjab Kings", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Nicholas Pooran": {"salaryCr": 21.0, "team": "Lucknow Super Giants", "bidder": "Lucknow Super Giants", "role": "Wicket-Keeper", "status": "Current squad salary / retained or acquired by franchise"},
  "Nishant Sindhu": {"salaryCr": 0.3, "team": "Gujarat Titans", "bidder": "Gujarat Titans", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Nitish Kumar Reddy": {"salaryCr": 6.0, "team": "Sunrisers Hyderabad", "bidder": "Sunrisers Hyderabad", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Noor Ahmad": {"salaryCr": 10.0, "team": "Chennai Super Kings", "bidder": "Chennai Super Kings", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Nuwan Thushara": {"salaryCr": 1.6, "team": "Royal Challengers Bengaluru", "bidder": "Royal Challengers Bengaluru", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Pat Cummins": {"salaryCr": 18.0, "team": "Sunrisers Hyderabad", "bidder": "Sunrisers Hyderabad", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Phil Salt": {"salaryCr": 11.5, "team": "Royal Challengers Bengaluru", "bidder": "Royal Challengers Bengaluru", "role": "Wicket-Keeper", "status": "Current squad salary / retained or acquired by franchise"},
  "Prabhsimran Singh": {"salaryCr": 4.0, "team": "Punjab Kings", "bidder": "Punjab Kings", "role": "Wicket-Keeper", "status": "Current squad salary / retained or acquired by franchise"},
  "Prashant Veer": {"salaryCr": 14.2, "team": "Chennai Super Kings", "bidder": "Chennai Super Kings", "role": "All-Rounder", "status": "2026 auction sold player (verified top-buy listing)"},
  "Prasidh Krishna": {"salaryCr": 9.5, "team": "Gujarat Titans", "bidder": "Gujarat Titans", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Prince Yadav": {"salaryCr": 0.3, "team": "Lucknow Super Giants", "bidder": "Lucknow Super Giants", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Priyansh Arya": {"salaryCr": 3.8, "team": "Punjab Kings", "bidder": "Punjab Kings", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Pyla Avinash": {"salaryCr": 0.3, "team": "Punjab Kings", "bidder": "Punjab Kings", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Raghu Sharma": {"salaryCr": 0.3, "team": "Mumbai Indians", "bidder": "Mumbai Indians", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Rahul Tewatia": {"salaryCr": 4.0, "team": "Gujarat Titans", "bidder": "Gujarat Titans", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Raj Angad Bawa": {"salaryCr": 0.3, "team": "Mumbai Indians", "bidder": "Mumbai Indians", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Rajat Patidar": {"salaryCr": 11.0, "team": "Royal Challengers Bengaluru", "bidder": "Royal Challengers Bengaluru", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Ramakrishna Ghosh": {"salaryCr": 0.3, "team": "Chennai Super Kings", "bidder": "Chennai Super Kings", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Ramandeep Singh": {"salaryCr": 4.0, "team": "Kolkata Knight Riders", "bidder": "Kolkata Knight Riders", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Rashid Khan": {"salaryCr": 18.0, "team": "Gujarat Titans", "bidder": "Gujarat Titans", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Rasikh Salam": {"salaryCr": 6.0, "team": "Royal Challengers Bengaluru", "bidder": "Royal Challengers Bengaluru", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Ravi Bishnoi": {"salaryCr": 7.2, "team": "Rajasthan Royals", "bidder": "Rajasthan Royals", "role": "Bowler", "status": "2026 auction sold player (verified top-buy listing)"},
  "Rinku Singh": {"salaryCr": 13.0, "team": "Kolkata Knight Riders", "bidder": "Kolkata Knight Riders", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Rishabh Pant": {"salaryCr": 27.0, "team": "Lucknow Super Giants", "bidder": "Lucknow Super Giants", "role": "Wicket-Keeper", "status": "Current squad salary / retained or acquired by franchise"},
  "Riyan Parag": {"salaryCr": 14.0, "team": "Rajasthan Royals", "bidder": "Rajasthan Royals", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Robin Minz": {"salaryCr": 0.65, "team": "Mumbai Indians", "bidder": "Mumbai Indians", "role": "Wicket-Keeper", "status": "Current squad salary / retained or acquired by franchise"},
  "Rohit Sharma": {"salaryCr": 16.3, "team": "Mumbai Indians", "bidder": "Mumbai Indians", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Romario Shepherd": {"salaryCr": 1.5, "team": "Royal Challengers Bengaluru", "bidder": "Royal Challengers Bengaluru", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Rovman Powell": {"salaryCr": 1.5, "team": "Kolkata Knight Riders", "bidder": "Kolkata Knight Riders", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Ruturaj Gaikwad": {"salaryCr": 18.0, "team": "Chennai Super Kings", "bidder": "Chennai Super Kings", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Ryan Rickelton": {"salaryCr": 1.0, "team": "Mumbai Indians", "bidder": "Mumbai Indians", "role": "Wicket-Keeper", "status": "Current squad salary / retained or acquired by franchise"},
  "Sai Kishore": {"salaryCr": 2.0, "team": "Gujarat Titans", "bidder": "Gujarat Titans", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Sai Sudharsan": {"salaryCr": 8.5, "team": "Gujarat Titans", "bidder": "Gujarat Titans", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Sameer Rizvi": {"salaryCr": 0.95, "team": "Delhi Capitals", "bidder": "Delhi Capitals", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Sandeep Sharma": {"salaryCr": 4.0, "team": "Rajasthan Royals", "bidder": "Rajasthan Royals", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Shahbaz Ahmed": {"salaryCr": 2.4, "team": "Lucknow Super Giants", "bidder": "Lucknow Super Giants", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Shahrukh Khan": {"salaryCr": 4.0, "team": "Gujarat Titans", "bidder": "Gujarat Titans", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Shashank Singh": {"salaryCr": 5.5, "team": "Punjab Kings", "bidder": "Punjab Kings", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Shimron Hetmyer": {"salaryCr": 11.0, "team": "Rajasthan Royals", "bidder": "Rajasthan Royals", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Shivam Dube": {"salaryCr": 12.0, "team": "Chennai Super Kings", "bidder": "Chennai Super Kings", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Shreyas Gopal": {"salaryCr": 0.3, "team": "Chennai Super Kings", "bidder": "Chennai Super Kings", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Shreyas Iyer": {"salaryCr": 26.75, "team": "Punjab Kings", "bidder": "Punjab Kings", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Shubham Dubey": {"salaryCr": 0.8, "team": "Rajasthan Royals", "bidder": "Rajasthan Royals", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Shubman Gill": {"salaryCr": 16.5, "team": "Gujarat Titans", "bidder": "Gujarat Titans", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Smaran Ravichandran": {"salaryCr": 0.3, "team": "Sunrisers Hyderabad", "bidder": "Sunrisers Hyderabad", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Sunil Narine": {"salaryCr": 12.0, "team": "Kolkata Knight Riders", "bidder": "Kolkata Knight Riders", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Suryakumar Yadav": {"salaryCr": 16.35, "team": "Mumbai Indians", "bidder": "Mumbai Indians", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Suryansh Shedge": {"salaryCr": 0.3, "team": "Punjab Kings", "bidder": "Punjab Kings", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Suyash Sharma": {"salaryCr": 2.6, "team": "Royal Challengers Bengaluru", "bidder": "Royal Challengers Bengaluru", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Swapnil Singh": {"salaryCr": 0.5, "team": "Royal Challengers Bengaluru", "bidder": "Royal Challengers Bengaluru", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "T Natarajan": {"salaryCr": 10.75, "team": "Delhi Capitals", "bidder": "Delhi Capitals", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Tilak Varma": {"salaryCr": 8.0, "team": "Mumbai Indians", "bidder": "Mumbai Indians", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Tim David": {"salaryCr": 3.0, "team": "Royal Challengers Bengaluru", "bidder": "Royal Challengers Bengaluru", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Travis Head": {"salaryCr": 14.0, "team": "Sunrisers Hyderabad", "bidder": "Sunrisers Hyderabad", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Trent Boult": {"salaryCr": 12.5, "team": "Mumbai Indians", "bidder": "Mumbai Indians", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Tripurana Vijay": {"salaryCr": 0.3, "team": "Delhi Capitals", "bidder": "Delhi Capitals", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Tristan Stubbs": {"salaryCr": 10.0, "team": "Delhi Capitals", "bidder": "Delhi Capitals", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Tushar Deshpande": {"salaryCr": 6.5, "team": "Rajasthan Royals", "bidder": "Rajasthan Royals", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Umran Malik": {"salaryCr": 0.75, "team": "Kolkata Knight Riders", "bidder": "Kolkata Knight Riders", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Urvil Patel": {"salaryCr": 0.3, "team": "Chennai Super Kings", "bidder": "Chennai Super Kings", "role": "Wicket-Keeper", "status": "Current squad salary / retained or acquired by franchise"},
  "Vaibhav Arora": {"salaryCr": 1.8, "team": "Kolkata Knight Riders", "bidder": "Kolkata Knight Riders", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Vaibhav Sooryavanshi": {"salaryCr": 1.1, "team": "Rajasthan Royals", "bidder": "Rajasthan Royals", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Varun Chakaravarthy": {"salaryCr": 12.0, "team": "Kolkata Knight Riders", "bidder": "Kolkata Knight Riders", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Venkatesh Iyer": {"salaryCr": 7.0, "team": "Royal Challengers Bengaluru", "bidder": "Royal Challengers Bengaluru", "role": "All-Rounder", "status": "2026 auction sold player (verified top-buy listing)"},
  "Vipraj Nigam": {"salaryCr": 0.5, "team": "Delhi Capitals", "bidder": "Delhi Capitals", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Virat Kohli": {"salaryCr": 21.0, "team": "Royal Challengers Bengaluru", "bidder": "Royal Challengers Bengaluru", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Vishnu Vinod": {"salaryCr": 0.95, "team": "Punjab Kings", "bidder": "Punjab Kings", "role": "Wicket-Keeper", "status": "Current squad salary / retained or acquired by franchise"},
  "Vyshak Vijaykumar": {"salaryCr": 1.8, "team": "Punjab Kings", "bidder": "Punjab Kings", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Washington Sundar": {"salaryCr": 3.2, "team": "Gujarat Titans", "bidder": "Gujarat Titans", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Will Jacks": {"salaryCr": 5.25, "team": "Mumbai Indians", "bidder": "Mumbai Indians", "role": "All-Rounder", "status": "Current squad salary / retained or acquired by franchise"},
  "Xavier Bartlett": {"salaryCr": 0.8, "team": "Punjab Kings", "bidder": "Punjab Kings", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Yash Dayal": {"salaryCr": 5.0, "team": "Royal Challengers Bengaluru", "bidder": "Royal Challengers Bengaluru", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Yash Thakur": {"salaryCr": 1.6, "team": "Punjab Kings", "bidder": "Punjab Kings", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Yashasvi Jaiswal": {"salaryCr": 18.0, "team": "Rajasthan Royals", "bidder": "Rajasthan Royals", "role": "Batter", "status": "Current squad salary / retained or acquired by franchise"},
  "Yudhvir Singh": {"salaryCr": 0.35, "team": "Rajasthan Royals", "bidder": "Rajasthan Royals", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Yuzvendra Chahal": {"salaryCr": 18.0, "team": "Punjab Kings", "bidder": "Punjab Kings", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
  "Zeeshan Ansari": {"salaryCr": 0.4, "team": "Sunrisers Hyderabad", "bidder": "Sunrisers Hyderabad", "role": "Bowler", "status": "Current squad salary / retained or acquired by franchise"},
}

export const auctionTeamSalaryTotals = {
  "Chennai Super Kings": 90,
  "Delhi Capitals": 104.15,
  "Gujarat Titans": 112.1,
  "Kolkata Knight Riders": 107.1,
  "Lucknow Super Giants": 100.35,
  "Mumbai Indians": 117.35,
  "Punjab Kings": 113.5,
  "Rajasthan Royals": 94.75,
  "Royal Challengers Bengaluru": 115.6,
  "Sunrisers Hyderabad": 112.5,
}

function normalizePlayerName(name) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '')
}

const salaryAnchorsByNormalizedName = Object.fromEntries(
  Object.entries(auctionSalaryAnchors).map(([name, value]) => [normalizePlayerName(name), value]),
)

const salaryAliases = {
  varunchakravarthy: 'varunchakaravarthy',
  tnatarajan: 'thangarasu natarajan'.replace(/[^a-z0-9]+/g, ''),
  auqibnabi: 'aquibnabi',
}

export function getAuctionSalaryAnchor(name) {
  const normalized = normalizePlayerName(name)
  return salaryAnchorsByNormalizedName[normalized] ?? salaryAnchorsByNormalizedName[salaryAliases[normalized]] ?? null
}

