export const cricketerProfiles = [
  {
    name: 'MS Dhoni',
    country: 'India',
    role: 'Wicketkeeper, finisher, captain',
    archetype: 'Calm finisher',
    wikipedia: 'https://en.wikipedia.org/wiki/MS_Dhoni',
    traits: { calm: 98, ambition: 78, risk: 54, creativity: 74, resilience: 92, leadership: 98, flair: 62, teamwork: 92 },
    matchLine: 'You stay quiet under pressure, read the room late, and make the final call when everyone else is rushing.',
    evidence: ['Captained India to major ICC titles', 'Known for finishing chases and composed decision-making', 'Wicketkeeper-batter with tactical control'],
  },
  {
    name: 'Virat Kohli',
    country: 'India',
    role: 'Top-order batter',
    archetype: 'Driven chase master',
    wikipedia: 'https://en.wikipedia.org/wiki/Virat_Kohli',
    traits: { calm: 66, ambition: 99, risk: 70, creativity: 76, resilience: 94, leadership: 88, flair: 86, teamwork: 82 },
    matchLine: 'You run on intensity, standards, and the need to turn pressure into proof.',
    evidence: ['Among the most prolific modern batters', 'Built a reputation in run chases', 'Former India captain with a high-performance image'],
  },
  {
    name: 'Sachin Tendulkar',
    country: 'India',
    role: 'Top-order batter',
    archetype: 'Master craftsman',
    wikipedia: 'https://en.wikipedia.org/wiki/Sachin_Tendulkar',
    traits: { calm: 88, ambition: 96, risk: 58, creativity: 82, resilience: 97, leadership: 70, flair: 86, teamwork: 84 },
    matchLine: 'You prefer mastery over noise, building greatness through repetition, patience, and range.',
    evidence: ['One of cricket history’s highest run scorers', 'Long international career across eras', 'Known for technical completeness'],
  },
  {
    name: 'Rohit Sharma',
    country: 'India',
    role: 'Opening batter, captain',
    archetype: 'Effortless strategist',
    wikipedia: 'https://en.wikipedia.org/wiki/Rohit_Sharma',
    traits: { calm: 86, ambition: 86, risk: 72, creativity: 78, resilience: 82, leadership: 90, flair: 88, teamwork: 86 },
    matchLine: 'You make hard things look unforced, then quietly organize people around a clear plan.',
    evidence: ['India captain across formats', 'Record-setting ODI double centuries', 'Successful franchise leadership'],
  },
  {
    name: 'Rahul Dravid',
    country: 'India',
    role: 'Top-order batter, coach',
    archetype: 'Patient wall',
    wikipedia: 'https://en.wikipedia.org/wiki/Rahul_Dravid',
    traits: { calm: 96, ambition: 84, risk: 34, creativity: 60, resilience: 99, leadership: 86, flair: 42, teamwork: 94 },
    matchLine: 'You are the person people trust when the situation needs discipline, patience, and substance.',
    evidence: ['Renowned Test batter nicknamed The Wall', 'Long career built on concentration', 'Later served as India coach'],
  },
  {
    name: 'Kapil Dev',
    country: 'India',
    role: 'Fast-bowling all-rounder, captain',
    archetype: 'Fearless pioneer',
    wikipedia: 'https://en.wikipedia.org/wiki/Kapil_Dev',
    traits: { calm: 74, ambition: 88, risk: 82, creativity: 74, resilience: 91, leadership: 94, flair: 80, teamwork: 88 },
    matchLine: 'You lead by doing the hard thing first and making others believe the impossible is possible.',
    evidence: ['Captained India to the 1983 Cricket World Cup', 'Elite Test all-rounder', 'Known for impact with bat and ball'],
  },
  {
    name: 'Sourav Ganguly',
    country: 'India',
    role: 'Top-order batter, captain',
    archetype: 'Bold builder',
    wikipedia: 'https://en.wikipedia.org/wiki/Sourav_Ganguly',
    traits: { calm: 68, ambition: 91, risk: 74, creativity: 70, resilience: 88, leadership: 96, flair: 78, teamwork: 90 },
    matchLine: 'You back people early, challenge old limits, and do not mind being seen taking a stand.',
    evidence: ['Former India captain', 'Credited with shaping a more assertive Indian team', 'Successful left-handed batter'],
  },
  {
    name: 'Yuvraj Singh',
    country: 'India',
    role: 'Batting all-rounder',
    archetype: 'Big-moment fighter',
    wikipedia: 'https://en.wikipedia.org/wiki/Yuvraj_Singh',
    traits: { calm: 70, ambition: 86, risk: 86, creativity: 82, resilience: 98, leadership: 72, flair: 92, teamwork: 84 },
    matchLine: 'You meet life’s biggest turns with style, courage, and the belief that one burst can change everything.',
    evidence: ['Player of the Tournament at the 2011 Cricket World Cup', 'Six sixes in an over at the 2007 World Twenty20', 'Known for major-match impact'],
  },
  {
    name: 'Jasprit Bumrah',
    country: 'India',
    role: 'Fast bowler',
    archetype: 'Precise disruptor',
    wikipedia: 'https://en.wikipedia.org/wiki/Jasprit_Bumrah',
    traits: { calm: 90, ambition: 86, risk: 62, creativity: 88, resilience: 88, leadership: 76, flair: 78, teamwork: 86 },
    matchLine: 'You solve problems with precision, unusual methods, and confidence when the margin is tiny.',
    evidence: ['Premier fast bowler across formats', 'Known for death bowling and yorkers', 'Distinctive action and tactical control'],
  },
  {
    name: 'Ravindra Jadeja',
    country: 'India',
    role: 'All-rounder',
    archetype: 'All-action stabilizer',
    wikipedia: 'https://en.wikipedia.org/wiki/Ravindra_Jadeja',
    traits: { calm: 82, ambition: 80, risk: 68, creativity: 68, resilience: 90, leadership: 72, flair: 78, teamwork: 96 },
    matchLine: 'You add value everywhere, often before people realize how much they depend on you.',
    evidence: ['Left-arm spin all-rounder', 'Elite fielder', 'Long-time India and IPL contributor'],
  },
  {
    name: 'Hardik Pandya',
    country: 'India',
    role: 'Fast-bowling all-rounder',
    archetype: 'Flash-point accelerator',
    wikipedia: 'https://en.wikipedia.org/wiki/Hardik_Pandya',
    traits: { calm: 66, ambition: 88, risk: 88, creativity: 78, resilience: 84, leadership: 82, flair: 94, teamwork: 80 },
    matchLine: 'You prefer visible stakes, fast turns, and moments where confidence has to become action.',
    evidence: ['Explosive all-rounder', 'Led Gujarat Titans to IPL success', 'Known for power-hitting and pace bowling'],
  },
  {
    name: 'Ravichandran Ashwin',
    country: 'India',
    role: 'Off-spin all-rounder',
    archetype: 'Tactical scientist',
    wikipedia: 'https://en.wikipedia.org/wiki/Ravichandran_Ashwin',
    traits: { calm: 86, ambition: 86, risk: 58, creativity: 94, resilience: 88, leadership: 76, flair: 62, teamwork: 82 },
    matchLine: 'You like understanding the system deeply, then winning with a smarter move than expected.',
    evidence: ['One of India’s leading Test wicket-takers', 'Known for variation and cricket intelligence', 'Useful lower-order batter'],
  },
  {
    name: 'Anil Kumble',
    country: 'India',
    role: 'Leg spinner, captain',
    archetype: 'Relentless problem-solver',
    wikipedia: 'https://en.wikipedia.org/wiki/Anil_Kumble',
    traits: { calm: 90, ambition: 88, risk: 44, creativity: 70, resilience: 98, leadership: 88, flair: 45, teamwork: 88 },
    matchLine: 'You win through persistence, accuracy, and the refusal to leave a problem alone.',
    evidence: ['619 Test wickets', 'Took all ten wickets in a Test innings', 'Former India captain and coach'],
  },
  {
    name: 'Virender Sehwag',
    country: 'India',
    role: 'Opening batter',
    archetype: 'Fearless opener',
    wikipedia: 'https://en.wikipedia.org/wiki/Virender_Sehwag',
    traits: { calm: 72, ambition: 84, risk: 98, creativity: 80, resilience: 76, leadership: 62, flair: 94, teamwork: 72 },
    matchLine: 'You do not wait for permission to be bold; you change the mood by attacking first.',
    evidence: ['Explosive Test and ODI opener', 'Scored two Test triple-centuries', 'Known for aggressive batting'],
  },
  {
    name: 'Gautam Gambhir',
    country: 'India',
    role: 'Opening batter',
    archetype: 'Intense competitor',
    wikipedia: 'https://en.wikipedia.org/wiki/Gautam_Gambhir',
    traits: { calm: 64, ambition: 90, risk: 66, creativity: 62, resilience: 92, leadership: 84, flair: 60, teamwork: 84 },
    matchLine: 'You are direct, demanding, and most comfortable when a result needs grit more than glamour.',
    evidence: ['Key innings in India’s 2007 and 2011 world title wins', 'Successful IPL captain', 'Known for competitive intensity'],
  },
  {
    name: 'Shubman Gill',
    country: 'India',
    role: 'Top-order batter',
    archetype: 'Polished riser',
    wikipedia: 'https://en.wikipedia.org/wiki/Shubman_Gill',
    traits: { calm: 84, ambition: 90, risk: 62, creativity: 74, resilience: 78, leadership: 70, flair: 82, teamwork: 76 },
    matchLine: 'You move with quiet confidence and like building a future that looks clean, modern, and controlled.',
    evidence: ['Top-order India batter', 'Rose from India U19 success', 'Known for elegant strokeplay'],
  },
  {
    name: 'Rishabh Pant',
    country: 'India',
    role: 'Wicketkeeper-batter',
    archetype: 'Instinctive game-changer',
    wikipedia: 'https://en.wikipedia.org/wiki/Rishabh_Pant',
    traits: { calm: 62, ambition: 86, risk: 96, creativity: 90, resilience: 90, leadership: 70, flair: 92, teamwork: 78 },
    matchLine: 'You trust your instinct, especially when the safe route feels too small for the moment.',
    evidence: ['Attacking wicketkeeper-batter', 'Known for match-winning Test innings overseas', 'Returned after a major accident'],
  },
  {
    name: 'KL Rahul',
    country: 'India',
    role: 'Top-order batter, wicketkeeper',
    archetype: 'Adaptable technician',
    wikipedia: 'https://en.wikipedia.org/wiki/KL_Rahul',
    traits: { calm: 82, ambition: 82, risk: 52, creativity: 70, resilience: 82, leadership: 76, flair: 72, teamwork: 86 },
    matchLine: 'You are flexible, polished, and willing to shift roles if the team needs a different version of you.',
    evidence: ['Has played as opener, middle-order batter, and wicketkeeper', 'India international across formats', 'IPL captaincy experience'],
  },
  {
    name: 'Suryakumar Yadav',
    country: 'India',
    role: 'T20 batter',
    archetype: '360-degree creator',
    wikipedia: 'https://en.wikipedia.org/wiki/Suryakumar_Yadav',
    traits: { calm: 72, ambition: 84, risk: 92, creativity: 98, resilience: 80, leadership: 70, flair: 96, teamwork: 76 },
    matchLine: 'You like inventing angles others do not see and turning routine situations into highlights.',
    evidence: ['Known for innovative T20 strokeplay', 'India T20I captaincy role', 'Top-ranked T20 batting reputation'],
  },
  {
    name: 'Mohammed Shami',
    country: 'India',
    role: 'Fast bowler',
    archetype: 'Rhythm hunter',
    wikipedia: 'https://en.wikipedia.org/wiki/Mohammed_Shami',
    traits: { calm: 82, ambition: 84, risk: 54, creativity: 62, resilience: 90, leadership: 68, flair: 58, teamwork: 84 },
    matchLine: 'You rely on rhythm, craft, and repeated pressure until an opening appears.',
    evidence: ['India fast bowler', 'Known for seam position and wicket-taking spells', 'Major World Cup performances'],
  },
  {
    name: 'Kane Williamson',
    country: 'New Zealand',
    role: 'Top-order batter, captain',
    archetype: 'Quiet architect',
    wikipedia: 'https://en.wikipedia.org/wiki/Kane_Williamson',
    traits: { calm: 99, ambition: 86, risk: 38, creativity: 76, resilience: 90, leadership: 94, flair: 58, teamwork: 96 },
    matchLine: 'You lead softly, think clearly, and make people better without demanding the spotlight.',
    evidence: ['Captained New Zealand to the World Test Championship title', 'Elite contemporary batter', 'Known for composure and sportsmanship'],
  },
  {
    name: 'AB de Villiers',
    country: 'South Africa',
    role: 'Batter, wicketkeeper',
    archetype: 'Inventive genius',
    wikipedia: 'https://en.wikipedia.org/wiki/AB_de_Villiers',
    traits: { calm: 82, ambition: 88, risk: 88, creativity: 99, resilience: 82, leadership: 76, flair: 98, teamwork: 82 },
    matchLine: 'You see more possibilities than most people and enjoy doing the impossible with ease.',
    evidence: ['Known for unorthodox shots around the wicket', 'Fastest ODI century record', 'Former South Africa captain'],
  },
  {
    name: 'Chris Gayle',
    country: 'West Indies',
    role: 'Opening batter',
    archetype: 'Power entertainer',
    wikipedia: 'https://en.wikipedia.org/wiki/Chris_Gayle',
    traits: { calm: 78, ambition: 82, risk: 92, creativity: 82, resilience: 80, leadership: 66, flair: 99, teamwork: 72 },
    matchLine: 'You bring presence, power, and a sense that life should have room for spectacle.',
    evidence: ['One of T20 cricket’s most destructive batters', 'Huge six-hitting record', 'West Indies title contributor'],
  },
  {
    name: 'Ben Stokes',
    country: 'England',
    role: 'All-rounder, captain',
    archetype: 'Crisis warrior',
    wikipedia: 'https://en.wikipedia.org/wiki/Ben_Stokes',
    traits: { calm: 70, ambition: 92, risk: 88, creativity: 76, resilience: 96, leadership: 90, flair: 88, teamwork: 92 },
    matchLine: 'You want the ball when everything is on the line, even if the path is messy.',
    evidence: ['Key figure in England’s 2019 World Cup win', 'England Test captain', 'Renowned all-rounder and pressure performer'],
  },
  {
    name: 'Joe Root',
    country: 'England',
    role: 'Top-order batter',
    archetype: 'Steady accumulator',
    wikipedia: 'https://en.wikipedia.org/wiki/Joe_Root',
    traits: { calm: 90, ambition: 90, risk: 48, creativity: 76, resilience: 92, leadership: 82, flair: 64, teamwork: 90 },
    matchLine: 'You keep scoring small wins until they become something too large to ignore.',
    evidence: ['One of England’s leading Test run scorers', 'Former England Test captain', 'Known for consistency and range'],
  },
  {
    name: 'Steve Smith',
    country: 'Australia',
    role: 'Top-order batter',
    archetype: 'Obsessive specialist',
    wikipedia: 'https://en.wikipedia.org/wiki/Steve_Smith_(cricketer)',
    traits: { calm: 78, ambition: 95, risk: 46, creativity: 88, resilience: 90, leadership: 74, flair: 68, teamwork: 78 },
    matchLine: 'You are at your best when you can obsess over details and win in your own strange, effective way.',
    evidence: ['Elite Test batter', 'Former Australia captain', 'Known for distinctive technique and concentration'],
  },
  {
    name: 'David Warner',
    country: 'Australia',
    role: 'Opening batter',
    archetype: 'High-energy starter',
    wikipedia: 'https://en.wikipedia.org/wiki/David_Warner_(cricketer)',
    traits: { calm: 58, ambition: 88, risk: 90, creativity: 74, resilience: 84, leadership: 70, flair: 86, teamwork: 78 },
    matchLine: 'You attack the first opening you see and set the tempo before others settle in.',
    evidence: ['Aggressive left-handed opener', 'World Cup and T20 World Cup winner', 'Successful IPL captain'],
  },
  {
    name: 'Pat Cummins',
    country: 'Australia',
    role: 'Fast bowler, captain',
    archetype: 'Composed commander',
    wikipedia: 'https://en.wikipedia.org/wiki/Pat_Cummins',
    traits: { calm: 94, ambition: 90, risk: 54, creativity: 66, resilience: 88, leadership: 94, flair: 58, teamwork: 92 },
    matchLine: 'You lead with calm authority and prefer doing difficult work without making it theatrical.',
    evidence: ['Australia captain', 'Fast bowler across formats', 'Led major title-winning sides'],
  },
  {
    name: 'Glenn Maxwell',
    country: 'Australia',
    role: 'Batting all-rounder',
    archetype: 'Chaos inventor',
    wikipedia: 'https://en.wikipedia.org/wiki/Glenn_Maxwell',
    traits: { calm: 58, ambition: 84, risk: 98, creativity: 98, resilience: 88, leadership: 66, flair: 98, teamwork: 76 },
    matchLine: 'You can turn disorder into opportunity and are comfortable trying the shot no one expected.',
    evidence: ['Explosive limited-overs all-rounder', 'Known for inventive batting', 'Historic 201 not out in the 2023 World Cup'],
  },
  {
    name: 'Shane Warne',
    country: 'Australia',
    role: 'Leg spinner',
    archetype: 'Magnetic tactician',
    wikipedia: 'https://en.wikipedia.org/wiki/Shane_Warne',
    traits: { calm: 74, ambition: 92, risk: 80, creativity: 94, resilience: 86, leadership: 82, flair: 96, teamwork: 78 },
    matchLine: 'You like the contest inside the contest: setting traps, reading people, and winning with theatre.',
    evidence: ['One of cricket’s greatest leg spinners', 'Over 700 Test wickets', 'Known for tactical showmanship'],
  },
  {
    name: 'Ricky Ponting',
    country: 'Australia',
    role: 'Batter, captain',
    archetype: 'Winning enforcer',
    wikipedia: 'https://en.wikipedia.org/wiki/Ricky_Ponting',
    traits: { calm: 72, ambition: 96, risk: 68, creativity: 70, resilience: 90, leadership: 96, flair: 80, teamwork: 88 },
    matchLine: 'You set high standards, expect others to meet them, and measure leadership by results.',
    evidence: ['Australia World Cup-winning captain', 'One of Australia’s leading run scorers', 'Dominant era leader'],
  },
  {
    name: 'Brian Lara',
    country: 'West Indies',
    role: 'Batter',
    archetype: 'Elegant record-breaker',
    wikipedia: 'https://en.wikipedia.org/wiki/Brian_Lara',
    traits: { calm: 78, ambition: 94, risk: 76, creativity: 92, resilience: 88, leadership: 74, flair: 98, teamwork: 70 },
    matchLine: 'You carry a sense of drama and artistry, especially when the challenge is huge.',
    evidence: ['Highest individual Test score of 400 not out', 'First-class 501 not out record', 'West Indies great'],
  },
  {
    name: 'Viv Richards',
    country: 'West Indies',
    role: 'Batter',
    archetype: 'Fearless presence',
    wikipedia: 'https://en.wikipedia.org/wiki/Viv_Richards',
    traits: { calm: 82, ambition: 94, risk: 86, creativity: 82, resilience: 90, leadership: 84, flair: 99, teamwork: 84 },
    matchLine: 'You bring authority into a room before saying much, then back it with fearless action.',
    evidence: ['West Indies batting great', 'Known for dominant attacking style', 'World Cup-winning era icon'],
  },
  {
    name: 'Jacques Kallis',
    country: 'South Africa',
    role: 'All-rounder',
    archetype: 'Complete professional',
    wikipedia: 'https://en.wikipedia.org/wiki/Jacques_Kallis',
    traits: { calm: 92, ambition: 90, risk: 44, creativity: 66, resilience: 96, leadership: 76, flair: 58, teamwork: 94 },
    matchLine: 'You are balanced, reliable, and valuable in more ways than people can easily summarize.',
    evidence: ['One of the greatest all-rounders', 'Huge Test runs and wickets record', 'South Africa mainstay'],
  },
  {
    name: 'Wasim Akram',
    country: 'Pakistan',
    role: 'Fast bowler, all-rounder',
    archetype: 'Swing artist',
    wikipedia: 'https://en.wikipedia.org/wiki/Wasim_Akram',
    traits: { calm: 80, ambition: 90, risk: 72, creativity: 94, resilience: 88, leadership: 82, flair: 88, teamwork: 84 },
    matchLine: 'You like skill with mystery: doing something difficult so smoothly that it looks natural.',
    evidence: ['Left-arm fast-bowling great', 'Reverse swing master', 'Former Pakistan captain'],
  },
  {
    name: 'Waqar Younis',
    country: 'Pakistan',
    role: 'Fast bowler',
    archetype: 'Relentless striker',
    wikipedia: 'https://en.wikipedia.org/wiki/Waqar_Younis',
    traits: { calm: 70, ambition: 90, risk: 76, creativity: 78, resilience: 90, leadership: 78, flair: 82, teamwork: 82 },
    matchLine: 'You believe direct pressure changes everything and prefer attacking the problem at full speed.',
    evidence: ['Pakistan fast-bowling great', 'Known for reverse swing and yorkers', 'Former captain and coach'],
  },
  {
    name: 'Babar Azam',
    country: 'Pakistan',
    role: 'Top-order batter',
    archetype: 'Polished anchor',
    wikipedia: 'https://en.wikipedia.org/wiki/Babar_Azam',
    traits: { calm: 86, ambition: 92, risk: 46, creativity: 72, resilience: 84, leadership: 82, flair: 74, teamwork: 84 },
    matchLine: 'You prefer elegant control: steady output, high expectations, and measured leadership.',
    evidence: ['Pakistan top-order batter', 'Former Pakistan captain in all formats', 'Champions Trophy winner'],
  },
  {
    name: 'Shaheen Afridi',
    country: 'Pakistan',
    role: 'Fast bowler',
    archetype: 'New-ball storm',
    wikipedia: 'https://en.wikipedia.org/wiki/Shaheen_Afridi',
    traits: { calm: 72, ambition: 88, risk: 76, creativity: 70, resilience: 82, leadership: 72, flair: 82, teamwork: 84 },
    matchLine: 'You like making an early statement and forcing everyone else to react to your energy.',
    evidence: ['Left-arm fast bowler', 'Known for new-ball wickets', 'Pakistan pace spearhead'],
  },
  {
    name: 'Shahid Afridi',
    country: 'Pakistan',
    role: 'All-rounder',
    archetype: 'Explosive wildcard',
    wikipedia: 'https://en.wikipedia.org/wiki/Shahid_Afridi',
    traits: { calm: 50, ambition: 86, risk: 99, creativity: 82, resilience: 78, leadership: 76, flair: 99, teamwork: 74 },
    matchLine: 'You are built for momentum swings, big gestures, and moments that no one can ignore.',
    evidence: ['Explosive all-rounder', 'Former Pakistan captain', 'Known for six-hitting and leg spin'],
  },
  {
    name: 'Kumar Sangakkara',
    country: 'Sri Lanka',
    role: 'Wicketkeeper-batter',
    archetype: 'Elegant thinker',
    wikipedia: 'https://en.wikipedia.org/wiki/Kumar_Sangakkara',
    traits: { calm: 92, ambition: 90, risk: 46, creativity: 78, resilience: 92, leadership: 88, flair: 82, teamwork: 90 },
    matchLine: 'You combine intelligence, polish, and empathy, often becoming the clearest voice in the room.',
    evidence: ['Sri Lanka batting great', 'Former captain and wicketkeeper', 'Highly respected cricket thinker'],
  },
  {
    name: 'Muttiah Muralitharan',
    country: 'Sri Lanka',
    role: 'Off spinner',
    archetype: 'Endless specialist',
    wikipedia: 'https://en.wikipedia.org/wiki/Muttiah_Muralitharan',
    traits: { calm: 86, ambition: 94, risk: 52, creativity: 94, resilience: 96, leadership: 72, flair: 70, teamwork: 88 },
    matchLine: 'You master one difficult craft so completely that it becomes your superpower.',
    evidence: ['Highest wicket-taker in Test cricket', 'Sri Lanka spin icon', 'Known for unusual spin craft'],
  },
  {
    name: 'Lasith Malinga',
    country: 'Sri Lanka',
    role: 'Fast bowler',
    archetype: 'Death-over specialist',
    wikipedia: 'https://en.wikipedia.org/wiki/Lasith_Malinga',
    traits: { calm: 82, ambition: 86, risk: 72, creativity: 92, resilience: 86, leadership: 72, flair: 90, teamwork: 84 },
    matchLine: 'You do your best work at the hardest point, using a style that nobody can quite copy.',
    evidence: ['Known for slingy action and yorkers', 'Sri Lanka limited-overs great', 'Death bowling specialist'],
  },
  {
    name: 'Sanath Jayasuriya',
    country: 'Sri Lanka',
    role: 'Opening batter, all-rounder',
    archetype: 'Powerplay revolutionary',
    wikipedia: 'https://en.wikipedia.org/wiki/Sanath_Jayasuriya',
    traits: { calm: 70, ambition: 88, risk: 94, creativity: 82, resilience: 84, leadership: 76, flair: 90, teamwork: 84 },
    matchLine: 'You change rules by acting before everyone agrees the rules can be changed.',
    evidence: ['Transformed ODI opening aggression', '1996 World Cup winner', 'Useful left-arm spin all-rounder'],
  },
  {
    name: 'Mahela Jayawardene',
    country: 'Sri Lanka',
    role: 'Batter, captain',
    archetype: 'Graceful planner',
    wikipedia: 'https://en.wikipedia.org/wiki/Mahela_Jayawardene',
    traits: { calm: 90, ambition: 86, risk: 50, creativity: 82, resilience: 88, leadership: 88, flair: 82, teamwork: 90 },
    matchLine: 'You prefer elegant solutions, long-range thinking, and calm communication.',
    evidence: ['Sri Lanka batting great', 'Former captain', 'Successful coaching and franchise roles'],
  },
  {
    name: 'Shakib Al Hasan',
    country: 'Bangladesh',
    role: 'All-rounder',
    archetype: 'Resourceful all-rounder',
    wikipedia: 'https://en.wikipedia.org/wiki/Shakib_Al_Hasan',
    traits: { calm: 76, ambition: 92, risk: 66, creativity: 76, resilience: 92, leadership: 84, flair: 72, teamwork: 88 },
    matchLine: 'You like carrying responsibility in multiple areas and finding value where others specialize.',
    evidence: ['Bangladesh’s leading all-rounder', 'Former national captain', 'Major contributor with bat and spin'],
  },
  {
    name: 'Rashid Khan',
    country: 'Afghanistan',
    role: 'Leg spinner',
    archetype: 'Fast-thinking spinner',
    wikipedia: 'https://en.wikipedia.org/wiki/Rashid_Khan',
    traits: { calm: 84, ambition: 92, risk: 68, creativity: 94, resilience: 88, leadership: 78, flair: 84, teamwork: 86 },
    matchLine: 'You learn fast, act faster, and use craft to compete with people who underestimate you.',
    evidence: ['Afghanistan cricket icon', 'Elite T20 leg spinner', 'Has captained Afghanistan'],
  },
  {
    name: 'Dwayne Bravo',
    country: 'West Indies',
    role: 'All-rounder',
    archetype: 'Joyful specialist',
    wikipedia: 'https://en.wikipedia.org/wiki/Dwayne_Bravo',
    traits: { calm: 76, ambition: 80, risk: 78, creativity: 88, resilience: 82, leadership: 74, flair: 96, teamwork: 92 },
    matchLine: 'You bring skill, rhythm, and personality to team moments, especially when timing matters.',
    evidence: ['T20 death-bowling specialist', 'West Indies title contributor', 'All-rounder and entertainer'],
  },
  {
    name: 'Kieron Pollard',
    country: 'West Indies',
    role: 'Power-hitting all-rounder',
    archetype: 'Finishing force',
    wikipedia: 'https://en.wikipedia.org/wiki/Kieron_Pollard',
    traits: { calm: 78, ambition: 84, risk: 86, creativity: 74, resilience: 84, leadership: 84, flair: 90, teamwork: 88 },
    matchLine: 'You prefer decisive late action, strong presence, and work that changes the result quickly.',
    evidence: ['T20 all-rounder', 'Former West Indies limited-overs captain', 'Long Mumbai Indians career'],
  },
  {
    name: 'Brendon McCullum',
    country: 'New Zealand',
    role: 'Wicketkeeper-batter, captain',
    archetype: 'Attacking culture-setter',
    wikipedia: 'https://en.wikipedia.org/wiki/Brendon_McCullum',
    traits: { calm: 70, ambition: 90, risk: 96, creativity: 88, resilience: 84, leadership: 92, flair: 94, teamwork: 90 },
    matchLine: 'You believe teams become braver when someone commits fully to an attacking idea.',
    evidence: ['Former New Zealand captain', 'Fastest Test century record', 'Influential attacking coach'],
  },
  {
    name: 'Eoin Morgan',
    country: 'England',
    role: 'Middle-order batter, captain',
    archetype: 'Culture engineer',
    wikipedia: 'https://en.wikipedia.org/wiki/Eoin_Morgan',
    traits: { calm: 88, ambition: 88, risk: 78, creativity: 86, resilience: 84, leadership: 96, flair: 74, teamwork: 94 },
    matchLine: 'You change outcomes by changing the group’s mindset, then trusting people to play freely.',
    evidence: ['Captained England to the 2019 Cricket World Cup', 'Transformed England’s limited-overs approach', 'Left-handed middle-order batter'],
  },
]

export const quizQuestions = [
  {
    prompt: 'A stressful week hits you all at once. What do you naturally do first?',
    options: [
      { label: 'Slow everything down and decide calmly', scores: { calm: 18, leadership: 8, resilience: 8 } },
      { label: 'Raise your standards and attack the hardest task', scores: { ambition: 18, resilience: 10, flair: 4 } },
      { label: 'Find a creative shortcut nobody else considered', scores: { creativity: 18, risk: 10, flair: 8 } },
      { label: 'Check on the people around you and stabilize the group', scores: { teamwork: 18, calm: 8, leadership: 8 } },
    ],
  },
  {
    prompt: 'In your friend group, which role fits you best?',
    options: [
      { label: 'The quiet decision-maker', scores: { calm: 16, leadership: 16 } },
      { label: 'The competitive motivator', scores: { ambition: 16, leadership: 12, resilience: 6 } },
      { label: 'The funny spark who changes the mood', scores: { flair: 18, creativity: 10, risk: 6 } },
      { label: 'The dependable one everyone leans on', scores: { teamwork: 18, resilience: 12, calm: 8 } },
    ],
  },
  {
    prompt: 'When life gives you a big opportunity, what is your instinct?',
    options: [
      { label: 'Prepare deeply, then execute cleanly', scores: { calm: 12, ambition: 12, resilience: 10 } },
      { label: 'Go bold before the moment passes', scores: { risk: 20, flair: 10, ambition: 8 } },
      { label: 'Look for the smartest angle', scores: { creativity: 18, calm: 8, leadership: 4 } },
      { label: 'Bring others with you', scores: { teamwork: 18, leadership: 12, calm: 6 } },
    ],
  },
  {
    prompt: 'What kind of compliment means the most to you?',
    options: [
      { label: 'You stayed composed when it mattered', scores: { calm: 18, resilience: 8 } },
      { label: 'You made everyone believe', scores: { leadership: 18, teamwork: 10 } },
      { label: 'You did something nobody expected', scores: { creativity: 16, risk: 12, flair: 8 } },
      { label: 'You never gave up', scores: { resilience: 20, ambition: 8 } },
    ],
  },
  {
    prompt: 'How do you usually handle rules and structure?',
    options: [
      { label: 'Respect the system and master it', scores: { calm: 12, resilience: 14, ambition: 8 } },
      { label: 'Bend it if there is a better way', scores: { creativity: 18, risk: 12 } },
      { label: 'Use it to organize the whole team', scores: { leadership: 16, teamwork: 12 } },
      { label: 'Challenge it directly', scores: { risk: 18, flair: 10, ambition: 8 } },
    ],
  },
  {
    prompt: 'Pick the life pace that feels most like you.',
    options: [
      { label: 'Measured and controlled', scores: { calm: 20, risk: -6 } },
      { label: 'Intense and goal-driven', scores: { ambition: 20, resilience: 8 } },
      { label: 'Spontaneous and expressive', scores: { flair: 18, risk: 12 } },
      { label: 'Balanced around people and priorities', scores: { teamwork: 18, leadership: 8, calm: 8 } },
    ],
  },
  {
    prompt: 'You fail at something important. What happens next?',
    options: [
      { label: 'I quietly rebuild the basics', scores: { resilience: 18, calm: 12 } },
      { label: 'I use it as fuel', scores: { resilience: 14, ambition: 16 } },
      { label: 'I change the method completely', scores: { creativity: 16, risk: 10 } },
      { label: 'I talk it through and reset with my people', scores: { teamwork: 18, calm: 8 } },
    ],
  },
  {
    prompt: 'What would your dream highlight moment look like?',
    options: [
      { label: 'A calm finish after everyone panicked', scores: { calm: 18, leadership: 10, resilience: 8 } },
      { label: 'A dominant performance everyone remembers', scores: { ambition: 18, flair: 12 } },
      { label: 'A wildly creative move that works', scores: { creativity: 20, risk: 12, flair: 10 } },
      { label: 'A team win where your role made the difference', scores: { teamwork: 20, leadership: 10 } },
    ],
  },
]
