export const cricketerProfiles = [
  {
    name: 'MS Dhoni',
    country: 'India',
    role: 'Wicketkeeper, finisher, captain',
    archetype: 'Calm finisher',
    wikipedia: 'https://en.wikipedia.org/wiki/MS_Dhoni',
    traits: { calm: 98, ambition: 78, risk: 54, creativity: 74, resilience: 92, leadership: 98, flair: 62, teamwork: 92 },
    matchLine: 'You stay quiet under pressure, read the room late, and make the final call when everyone else is rushing.',
    evidence: ['Captained India to major ICC titles', 'Known for finishing chases and composed decision-making', 'Wicketkeeper-batter with tactical control'],
  },
  {
    name: 'Virat Kohli',
    country: 'India',
    role: 'Top-order batter',
    archetype: 'Driven chase master',
    wikipedia: 'https://en.wikipedia.org/wiki/Virat_Kohli',
    traits: { calm: 66, ambition: 99, risk: 70, creativity: 76, resilience: 94, leadership: 88, flair: 86, teamwork: 82 },
    matchLine: 'You run on intensity, standards, and the need to turn pressure into proof.',
    evidence: ['Among the most prolific modern batters', 'Built a reputation in run chases', 'Former India captain with a high-performance image'],
  },
  {
    name: 'Sachin Tendulkar',
    country: 'India',
    role: 'Top-order batter',
    archetype: 'Master craftsman',
    wikipedia: 'https://en.wikipedia.org/wiki/Sachin_Tendulkar',
    traits: { calm: 88, ambition: 96, risk: 58, creativity: 82, resilience: 97, leadership: 70, flair: 86, teamwork: 84 },
    matchLine: 'You prefer mastery over noise, building greatness through repetition, patience, and range.',
    evidence: ['One of cricket history’s highest run scorers', 'Long international career across eras', 'Known for technical completeness'],
  },
  {
    name: 'Rohit Sharma',
    country: 'India',
    role: 'Opening batter, captain',
    archetype: 'Effortless strategist',
    wikipedia: 'https://en.wikipedia.org/wiki/Rohit_Sharma',
    traits: { calm: 86, ambition: 86, risk: 72, creativity: 78, resilience: 82, leadership: 90, flair: 88, teamwork: 86 },
    matchLine: 'You make hard things look unforced, then quietly organize people around a clear plan.',
    evidence: ['India captain across formats', 'Record-setting ODI double centuries', 'Successful franchise leadership'],
  },
  {
    name: 'Rahul Dravid',
    country: 'India',
    role: 'Top-order batter, coach',
    archetype: 'Patient wall',
    wikipedia: 'https://en.wikipedia.org/wiki/Rahul_Dravid',
    traits: { calm: 96, ambition: 84, risk: 34, creativity: 60, resilience: 99, leadership: 86, flair: 42, teamwork: 94 },
    matchLine: 'You are the person people trust when the situation needs discipline, patience, and substance.',
    evidence: ['Renowned Test batter nicknamed The Wall', 'Long career built on concentration', 'Later served as India coach'],
  },
  {
    name: 'Kapil Dev',
    country: 'India',
    role: 'Fast-bowling all-rounder, captain',
    archetype: 'Fearless pioneer',
    wikipedia: 'https://en.wikipedia.org/wiki/Kapil_Dev',
    traits: { calm: 74, ambition: 88, risk: 82, creativity: 74, resilience: 91, leadership: 94, flair: 80, teamwork: 88 },
    matchLine: 'You lead by doing the hard thing first and making others believe the impossible is possible.',
    evidence: ['Captained India to the 1983 Cricket World Cup', 'Elite Test all-rounder', 'Known for impact with bat and ball'],
  },
  {
    name: 'Sourav Ganguly',
    country: 'India',
    role: 'Top-order batter, captain',
    archetype: 'Bold builder',
    wikipedia: 'https://en.wikipedia.org/wiki/Sourav_Ganguly',
    traits: { calm: 68, ambition: 91, risk: 74, creativity: 70, resilience: 88, leadership: 96, flair: 78, teamwork: 90 },
    matchLine: 'You back people early, challenge old limits, and do not mind being seen taking a stand.',
    evidence: ['Former India captain', 'Credited with shaping a more assertive Indian team', 'Successful left-handed batter'],
  },
  {
    name: 'Yuvraj Singh',
    country: 'India',
    role: 'Batting all-rounder',
    archetype: 'Big-moment fighter',
    wikipedia: 'https://en.wikipedia.org/wiki/Yuvraj_Singh',
    traits: { calm: 70, ambition: 86, risk: 86, creativity: 82, resilience: 98, leadership: 72, flair: 92, teamwork: 84 },
    matchLine: 'You meet life’s biggest turns with style, courage, and the belief that one burst can change everything.',
    evidence: ['Player of the Tournament at the 2011 Cricket World Cup', 'Six sixes in an over at the 2007 World Twenty20', 'Known for major-match impact'],
  },
  {
    name: 'Jasprit Bumrah',
    country: 'India',
    role: 'Fast bowler',
    archetype: 'Precise disruptor',
    wikipedia: 'https://en.wikipedia.org/wiki/Jasprit_Bumrah',
    traits: { calm: 90, ambition: 86, risk: 62, creativity: 88, resilience: 88, leadership: 76, flair: 78, teamwork: 86 },
    matchLine: 'You solve problems with precision, unusual methods, and confidence when the margin is tiny.',
    evidence: ['Premier fast bowler across formats', 'Known for death bowling and yorkers', 'Distinctive action and tactical control'],
  },
  {
    name: 'Ravindra Jadeja',
    country: 'India',
    role: 'All-rounder',
    archetype: 'All-action stabilizer',
    wikipedia: 'https://en.wikipedia.org/wiki/Ravindra_Jadeja',
    traits: { calm: 82, ambition: 80, risk: 68, creativity: 68, resilience: 90, leadership: 72, flair: 78, teamwork: 96 },
    matchLine: 'You add value everywhere, often before people realize how much they depend on you.',
    evidence: ['Left-arm spin all-rounder', 'Elite fielder', 'Long-time India and IPL contributor'],
  },
  {
    name: 'Hardik Pandya',
    country: 'India',
    role: 'Fast-bowling all-rounder',
    archetype: 'Flash-point accelerator',
    wikipedia: 'https://en.wikipedia.org/wiki/Hardik_Pandya',
    traits: { calm: 66, ambition: 88, risk: 88, creativity: 78, resilience: 84, leadership: 82, flair: 94, teamwork: 80 },
    matchLine: 'You prefer visible stakes, fast turns, and moments where confidence has to become action.',
    evidence: ['Explosive all-rounder', 'Led Gujarat Titans to IPL success', 'Known for power-hitting and pace bowling'],
  },
  {
    name: 'Ravichandran Ashwin',
    country: 'India',
    role: 'Off-spin all-rounder',
    archetype: 'Tactical scientist',
    wikipedia: 'https://en.wikipedia.org/wiki/Ravichandran_Ashwin',
    traits: { calm: 86, ambition: 86, risk: 58, creativity: 94, resilience: 88, leadership: 76, flair: 62, teamwork: 82 },
    matchLine: 'You like understanding the system deeply, then winning with a smarter move than expected.',
    evidence: ['One of India’s leading Test wicket-takers', 'Known for variation and cricket intelligence', 'Useful lower-order batter'],
  },
  {
    name: 'Anil Kumble',
    country: 'India',
    role: 'Leg spinner, captain',
    archetype: 'Relentless problem-solver',
    wikipedia: 'https://en.wikipedia.org/wiki/Anil_Kumble',
    traits: { calm: 90, ambition: 88, risk: 44, creativity: 70, resilience: 98, leadership: 88, flair: 45, teamwork: 88 },
    matchLine: 'You win through persistence, accuracy, and the refusal to leave a problem alone.',
    evidence: ['619 Test wickets', 'Took all ten wickets in a Test innings', 'Former India captain and coach'],
  },
  {
    name: 'Virender Sehwag',
    country: 'India',
    role: 'Opening batter',
    archetype: 'Fearless opener',
    wikipedia: 'https://en.wikipedia.org/wiki/Virender_Sehwag',
    traits: { calm: 72, ambition: 84, risk: 98, creativity: 80, resilience: 76, leadership: 62, flair: 94, teamwork: 72 },
    matchLine: 'You do not wait for permission to be bold; you change the mood by attacking first.',
    evidence: ['Explosive Test and ODI opener', 'Scored two Test triple-centuries', 'Known for aggressive batting'],
  },
  {
    name: 'Gautam Gambhir',
    country: 'India',
    role: 'Opening batter',
    archetype: 'Intense competitor',
    wikipedia: 'https://en.wikipedia.org/wiki/Gautam_Gambhir',
    traits: { calm: 64, ambition: 90, risk: 66, creativity: 62, resilience: 92, leadership: 84, flair: 60, teamwork: 84 },
    matchLine: 'You are direct, demanding, and most comfortable when a result needs grit more than glamour.',
    evidence: ['Key innings in India’s 2007 and 2011 world title wins', 'Successful IPL captain', 'Known for competitive intensity'],
  },
  {
    name: 'Shubman Gill',
    country: 'India',
    role: 'Top-order batter',
    archetype: 'Polished riser',
    wikipedia: 'https://en.wikipedia.org/wiki/Shubman_Gill',
    traits: { calm: 84, ambition: 90, risk: 62, creativity: 74, resilience: 78, leadership: 70, flair: 82, teamwork: 76 },
    matchLine: 'You move with quiet confidence and like building a future that looks clean, modern, and controlled.',
    evidence: ['Top-order India batter', 'Rose from India U19 success', 'Known for elegant strokeplay'],
  },
  {
    name: 'Rishabh Pant',
    country: 'India',
    role: 'Wicketkeeper-batter',
    archetype: 'Instinctive game-changer',
    wikipedia: 'https://en.wikipedia.org/wiki/Rishabh_Pant',
    traits: { calm: 62, ambition: 86, risk: 96, creativity: 90, resilience: 90, leadership: 70, flair: 92, teamwork: 78 },
    matchLine: 'You trust your instinct, especially when the safe route feels too small for the moment.',
    evidence: ['Attacking wicketkeeper-batter', 'Known for match-winning Test innings overseas', 'Returned after a major accident'],
  },
  {
    name: 'KL Rahul',
    country: 'India',
    role: 'Top-order batter, wicketkeeper',
    archetype: 'Adaptable technician',
    wikipedia: 'https://en.wikipedia.org/wiki/KL_Rahul',
    traits: { calm: 82, ambition: 82, risk: 52, creativity: 70, resilience: 82, leadership: 76, flair: 72, teamwork: 86 },
    matchLine: 'You are flexible, polished, and willing to shift roles if the team needs a different version of you.',
    evidence: ['Has played as opener, middle-order batter, and wicketkeeper', 'India international across formats', 'IPL captaincy experience'],
  },
  {
    name: 'Suryakumar Yadav',
    country: 'India',
    role: 'T20 batter',
    archetype: '360-degree creator',
    wikipedia: 'https://en.wikipedia.org/wiki/Suryakumar_Yadav',
    traits: { calm: 72, ambition: 84, risk: 92, creativity: 98, resilience: 80, leadership: 70, flair: 96, teamwork: 76 },
    matchLine: 'You like inventing angles others do not see and turning routine situations into highlights.',
    evidence: ['Known for innovative T20 strokeplay', 'India T20I captaincy role', 'Top-ranked T20 batting reputation'],
  },
  {
    name: 'Mohammed Shami',
    country: 'India',
    role: 'Fast bowler',
    archetype: 'Rhythm hunter',
    wikipedia: 'https://en.wikipedia.org/wiki/Mohammed_Shami',
    traits: { calm: 82, ambition: 84, risk: 54, creativity: 62, resilience: 90, leadership: 68, flair: 58, teamwork: 84 },
    matchLine: 'You rely on rhythm, craft, and repeated pressure until an opening appears.',
    evidence: ['India fast bowler', 'Known for seam position and wicket-taking spells', 'Major World Cup performances'],
  },
  {
    name: 'Kane Williamson',
    country: 'New Zealand',
    role: 'Top-order batter, captain',
    archetype: 'Quiet architect',
    wikipedia: 'https://en.wikipedia.org/wiki/Kane_Williamson',
    traits: { calm: 99, ambition: 86, risk: 38, creativity: 76, resilience: 90, leadership: 94, flair: 58, teamwork: 96 },
    matchLine: 'You lead softly, think clearly, and make people better without demanding the spotlight.',
    evidence: ['Captained New Zealand to the World Test Championship title', 'Elite contemporary batter', 'Known for composure and sportsmanship'],
  },
  {
    name: 'AB de Villiers',
    country: 'South Africa',
    role: 'Batter, wicketkeeper',
    archetype: 'Inventive genius',
    wikipedia: 'https://en.wikipedia.org/wiki/AB_de_Villiers',
    traits: { calm: 82, ambition: 88, risk: 88, creativity: 99, resilience: 82, leadership: 76, flair: 98, teamwork: 82 },
    matchLine: 'You see more possibilities than most people and enjoy doing the impossible with ease.',
    evidence: ['Known for unorthodox shots around the wicket', 'Fastest ODI century record', 'Former South Africa captain'],
  },
  {
    name: 'Chris Gayle',
    country: 'West Indies',
    role: 'Opening batter',
    archetype: 'Power entertainer',
    wikipedia: 'https://en.wikipedia.org/wiki/Chris_Gayle',
    traits: { calm: 78, ambition: 82, risk: 92, creativity: 82, resilience: 80, leadership: 66, flair: 99, teamwork: 72 },
    matchLine: 'You bring presence, power, and a sense that life should have room for spectacle.',
    evidence: ['One of T20 cricket’s most destructive batters', 'Huge six-hitting record', 'West Indies title contributor'],
  },
  {
    name: 'Ben Stokes',
    country: 'England',
    role: 'All-rounder, captain',
    archetype: 'Crisis warrior',
    wikipedia: 'https://en.wikipedia.org/wiki/Ben_Stokes',
    traits: { calm: 70, ambition: 92, risk: 88, creativity: 76, resilience: 96, leadership: 90, flair: 88, teamwork: 92 },
    matchLine: 'You want the ball when everything is on the line, even if the path is messy.',
    evidence: ['Key figure in England’s 2019 World Cup win', 'England Test captain', 'Renowned all-rounder and pressure performer'],
  },
  {
    name: 'Joe Root',
    country: 'England',
    role: 'Top-order batter',
    archetype: 'Steady accumulator',
    wikipedia: 'https://en.wikipedia.org/wiki/Joe_Root',
    traits: { calm: 90, ambition: 90, risk: 48, creativity: 76, resilience: 92, leadership: 82, flair: 64, teamwork: 90 },
    matchLine: 'You keep scoring small wins until they become something too large to ignore.',
    evidence: ['One of England’s leading Test run scorers', 'Former England Test captain', 'Known for consistency and range'],
  },
  {
    name: 'Steve Smith',
    country: 'Australia',
    role: 'Top-order batter',
    archetype: 'Obsessive specialist',
    wikipedia: 'https://en.wikipedia.org/wiki/Steve_Smith_(cricketer)',
    traits: { calm: 78, ambition: 95, risk: 46, creativity: 88, resilience: 90, leadership: 74, flair: 68, teamwork: 78 },
    matchLine: 'You are at your best when you can obsess over details and win in your own strange, effective way.',
    evidence: ['Elite Test batter', 'Former Australia captain', 'Known for distinctive technique and concentration'],
  },
  {
    name: 'David Warner',
    country: 'Australia',
    role: 'Opening batter',
    archetype: 'High-energy starter',
    wikipedia: 'https://en.wikipedia.org/wiki/David_Warner_(cricketer)',
    traits: { calm: 58, ambition: 88, risk: 90, creativity: 74, resilience: 84, leadership: 70, flair: 86, teamwork: 78 },
    matchLine: 'You attack the first opening you see and set the tempo before others settle in.',
    evidence: ['Aggressive left-handed opener', 'World Cup and T20 World Cup winner', 'Successful IPL captain'],
  },
  {
    name: 'Pat Cummins',
    country: 'Australia',
    role: 'Fast bowler, captain',
    archetype: 'Composed commander',
    wikipedia: 'https://en.wikipedia.org/wiki/Pat_Cummins',
    traits: { calm: 94, ambition: 90, risk: 54, creativity: 66, resilience: 88, leadership: 94, flair: 58, teamwork: 92 },
    matchLine: 'You lead with calm authority and prefer doing difficult work without making it theatrical.',
    evidence: ['Australia captain', 'Fast bowler across formats', 'Led major title-winning sides'],
  },
  {
    name: 'Glenn Maxwell',
    country: 'Australia',
    role: 'Batting all-rounder',
    archetype: 'Chaos inventor',
    wikipedia: 'https://en.wikipedia.org/wiki/Glenn_Maxwell',
    traits: { calm: 58, ambition: 84, risk: 98, creativity: 98, resilience: 88, leadership: 66, flair: 98, teamwork: 76 },
    matchLine: 'You can turn disorder into opportunity and are comfortable trying the shot no one expected.',
    evidence: ['Explosive limited-overs all-rounder', 'Known for inventive batting', 'Historic 201 not out in the 2023 World Cup'],
  },
  {
    name: 'Shane Warne',
    country: 'Australia',
    role: 'Leg spinner',
    archetype: 'Magnetic tactician',
    wikipedia: 'https://en.wikipedia.org/wiki/Shane_Warne',
    traits: { calm: 74, ambition: 92, risk: 80, creativity: 94, resilience: 86, leadership: 82, flair: 96, teamwork: 78 },
    matchLine: 'You like the contest inside the contest: setting traps, reading people, and winning with theatre.',
    evidence: ['One of cricket’s greatest leg spinners', 'Over 700 Test wickets', 'Known for tactical showmanship'],
  },
  {
    name: 'Ricky Ponting',
    country: 'Australia',
    role: 'Batter, captain',
    archetype: 'Winning enforcer',
    wikipedia: 'https://en.wikipedia.org/wiki/Ricky_Ponting',
    traits: { calm: 72, ambition: 96, risk: 68, creativity: 70, resilience: 90, leadership: 96, flair: 80, teamwork: 88 },
    matchLine: 'You set high standards, expect others to meet them, and measure leadership by results.',
    evidence: ['Australia World Cup-winning captain', 'One of Australia’s leading run scorers', 'Dominant era leader'],
  },
  {
    name: 'Brian Lara',
    country: 'West Indies',
    role: 'Batter',
    archetype: 'Elegant record-breaker',
    wikipedia: 'https://en.wikipedia.org/wiki/Brian_Lara',
    traits: { calm: 78, ambition: 94, risk: 76, creativity: 92, resilience: 88, leadership: 74, flair: 98, teamwork: 70 },
    matchLine: 'You carry a sense of drama and artistry, especially when the challenge is huge.',
    evidence: ['Highest individual Test score of 400 not out', 'First-class 501 not out record', 'West Indies great'],
  },
  {
    name: 'Viv Richards',
    country: 'West Indies',
    role: 'Batter',
    archetype: 'Fearless presence',
    wikipedia: 'https://en.wikipedia.org/wiki/Viv_Richards',
    traits: { calm: 82, ambition: 94, risk: 86, creativity: 82, resilience: 90, leadership: 84, flair: 99, teamwork: 84 },
    matchLine: 'You bring authority into a room before saying much, then back it with fearless action.',
    evidence: ['West Indies batting great', 'Known for dominant attacking style', 'World Cup-winning era icon'],
  },
  {
    name: 'Jacques Kallis',
    country: 'South Africa',
    role: 'All-rounder',
    archetype: 'Complete professional',
    wikipedia: 'https://en.wikipedia.org/wiki/Jacques_Kallis',
    traits: { calm: 92, ambition: 90, risk: 44, creativity: 66, resilience: 96, leadership: 76, flair: 58, teamwork: 94 },
    matchLine: 'You are balanced, reliable, and valuable in more ways than people can easily summarize.',
    evidence: ['One of the greatest all-rounders', 'Huge Test runs and wickets record', 'South Africa mainstay'],
  },
  {
    name: 'Wasim Akram',
    country: 'Pakistan',
    role: 'Fast bowler, all-rounder',
    archetype: 'Swing artist',
    wikipedia: 'https://en.wikipedia.org/wiki/Wasim_Akram',
    traits: { calm: 80, ambition: 90, risk: 72, creativity: 94, resilience: 88, leadership: 82, flair: 88, teamwork: 84 },
    matchLine: 'You like skill with mystery: doing something difficult so smoothly that it looks natural.',
    evidence: ['Left-arm fast-bowling great', 'Reverse swing master', 'Former Pakistan captain'],
  },
  {
    name: 'Waqar Younis',
    country: 'Pakistan',
    role: 'Fast bowler',
    archetype: 'Relentless striker',
    wikipedia: 'https://en.wikipedia.org/wiki/Waqar_Younis',
    traits: { calm: 70, ambition: 90, risk: 76, creativity: 78, resilience: 90, leadership: 78, flair: 82, teamwork: 82 },
    matchLine: 'You believe direct pressure changes everything and prefer attacking the problem at full speed.',
    evidence: ['Pakistan fast-bowling great', 'Known for reverse swing and yorkers', 'Former captain and coach'],
  },
  {
    name: 'Babar Azam',
    country: 'Pakistan',
    role: 'Top-order batter',
    archetype: 'Polished anchor',
    wikipedia: 'https://en.wikipedia.org/wiki/Babar_Azam',
    traits: { calm: 86, ambition: 92, risk: 46, creativity: 72, resilience: 84, leadership: 82, flair: 74, teamwork: 84 },
    matchLine: 'You prefer elegant control: steady output, high expectations, and measured leadership.',
    evidence: ['Pakistan top-order batter', 'Former Pakistan captain in all formats', 'Champions Trophy winner'],
  },
  {
    name: 'Shaheen Afridi',
    country: 'Pakistan',
    role: 'Fast bowler',
    archetype: 'New-ball storm',
    wikipedia: 'https://en.wikipedia.org/wiki/Shaheen_Afridi',
    traits: { calm: 72, ambition: 88, risk: 76, creativity: 70, resilience: 82, leadership: 72, flair: 82, teamwork: 84 },
    matchLine: 'You like making an early statement and forcing everyone else to react to your energy.',
    evidence: ['Left-arm fast bowler', 'Known for new-ball wickets', 'Pakistan pace spearhead'],
  },
  {
    name: 'Shahid Afridi',
    country: 'Pakistan',
    role: 'All-rounder',
    archetype: 'Explosive wildcard',
    wikipedia: 'https://en.wikipedia.org/wiki/Shahid_Afridi',
    traits: { calm: 50, ambition: 86, risk: 99, creativity: 82, resilience: 78, leadership: 76, flair: 99, teamwork: 74 },
    matchLine: 'You are built for momentum swings, big gestures, and moments that no one can ignore.',
    evidence: ['Explosive all-rounder', 'Former Pakistan captain', 'Known for six-hitting and leg spin'],
  },
  {
    name: 'Kumar Sangakkara',
    country: 'Sri Lanka',
    role: 'Wicketkeeper-batter',
    archetype: 'Elegant thinker',
    wikipedia: 'https://en.wikipedia.org/wiki/Kumar_Sangakkara',
    traits: { calm: 92, ambition: 90, risk: 46, creativity: 78, resilience: 92, leadership: 88, flair: 82, teamwork: 90 },
    matchLine: 'You combine intelligence, polish, and empathy, often becoming the clearest voice in the room.',
    evidence: ['Sri Lanka batting great', 'Former captain and wicketkeeper', 'Highly respected cricket thinker'],
  },
  {
    name: 'Muttiah Muralitharan',
    country: 'Sri Lanka',
    role: 'Off spinner',
    archetype: 'Endless specialist',
    wikipedia: 'https://en.wikipedia.org/wiki/Muttiah_Muralitharan',
    traits: { calm: 86, ambition: 94, risk: 52, creativity: 94, resilience: 96, leadership: 72, flair: 70, teamwork: 88 },
    matchLine: 'You master one difficult craft so completely that it becomes your superpower.',
    evidence: ['Highest wicket-taker in Test cricket', 'Sri Lanka spin icon', 'Known for unusual spin craft'],
  },
  {
    name: 'Lasith Malinga',
    country: 'Sri Lanka',
    role: 'Fast bowler',
    archetype: 'Death-over specialist',
    wikipedia: 'https://en.wikipedia.org/wiki/Lasith_Malinga',
    traits: { calm: 82, ambition: 86, risk: 72, creativity: 92, resilience: 86, leadership: 72, flair: 90, teamwork: 84 },
    matchLine: 'You do your best work at the hardest point, using a style that nobody can quite copy.',
    evidence: ['Known for slingy action and yorkers', 'Sri Lanka limited-overs great', 'Death bowling specialist'],
  },
  {
    name: 'Sanath Jayasuriya',
    country: 'Sri Lanka',
    role: 'Opening batter, all-rounder',
    archetype: 'Powerplay revolutionary',
    wikipedia: 'https://en.wikipedia.org/wiki/Sanath_Jayasuriya',
    traits: { calm: 70, ambition: 88, risk: 94, creativity: 82, resilience: 84, leadership: 76, flair: 90, teamwork: 84 },
    matchLine: 'You change rules by acting before everyone agrees the rules can be changed.',
    evidence: ['Transformed ODI opening aggression', '1996 World Cup winner', 'Useful left-arm spin all-rounder'],
  },
  {
    name: 'Mahela Jayawardene',
    country: 'Sri Lanka',
    role: 'Batter, captain',
    archetype: 'Graceful planner',
    wikipedia: 'https://en.wikipedia.org/wiki/Mahela_Jayawardene',
    traits: { calm: 90, ambition: 86, risk: 50, creativity: 82, resilience: 88, leadership: 88, flair: 82, teamwork: 90 },
    matchLine: 'You prefer elegant solutions, long-range thinking, and calm communication.',
    evidence: ['Sri Lanka batting great', 'Former captain', 'Successful coaching and franchise roles'],
  },
  {
    name: 'Shakib Al Hasan',
    country: 'Bangladesh',
    role: 'All-rounder',
    archetype: 'Resourceful all-rounder',
    wikipedia: 'https://en.wikipedia.org/wiki/Shakib_Al_Hasan',
    traits: { calm: 76, ambition: 92, risk: 66, creativity: 76, resilience: 92, leadership: 84, flair: 72, teamwork: 88 },
    matchLine: 'You like carrying responsibility in multiple areas and finding value where others specialize.',
    evidence: ['Bangladesh’s leading all-rounder', 'Former national captain', 'Major contributor with bat and spin'],
  },
  {
    name: 'Rashid Khan',
    country: 'Afghanistan',
    role: 'Leg spinner',
    archetype: 'Fast-thinking spinner',
    wikipedia: 'https://en.wikipedia.org/wiki/Rashid_Khan',
    traits: { calm: 84, ambition: 92, risk: 68, creativity: 94, resilience: 88, leadership: 78, flair: 84, teamwork: 86 },
    matchLine: 'You learn fast, act faster, and use craft to compete with people who underestimate you.',
    evidence: ['Afghanistan cricket icon', 'Elite T20 leg spinner', 'Has captained Afghanistan'],
  },
  {
    name: 'Dwayne Bravo',
    country: 'West Indies',
    role: 'All-rounder',
    archetype: 'Joyful specialist',
    wikipedia: 'https://en.wikipedia.org/wiki/Dwayne_Bravo',
    traits: { calm: 76, ambition: 80, risk: 78, creativity: 88, resilience: 82, leadership: 74, flair: 96, teamwork: 92 },
    matchLine: 'You bring skill, rhythm, and personality to team moments, especially when timing matters.',
    evidence: ['T20 death-bowling specialist', 'West Indies title contributor', 'All-rounder and entertainer'],
  },
  {
    name: 'Kieron Pollard',
    country: 'West Indies',
    role: 'Power-hitting all-rounder',
    archetype: 'Finishing force',
    wikipedia: 'https://en.wikipedia.org/wiki/Kieron_Pollard',
    traits: { calm: 78, ambition: 84, risk: 86, creativity: 74, resilience: 84, leadership: 84, flair: 90, teamwork: 88 },
    matchLine: 'You prefer decisive late action, strong presence, and work that changes the result quickly.',
    evidence: ['T20 all-rounder', 'Former West Indies limited-overs captain', 'Long Mumbai Indians career'],
  },
  {
    name: 'Brendon McCullum',
    country: 'New Zealand',
    role: 'Wicketkeeper-batter, captain',
    archetype: 'Attacking culture-setter',
    wikipedia: 'https://en.wikipedia.org/wiki/Brendon_McCullum',
    traits: { calm: 70, ambition: 90, risk: 96, creativity: 88, resilience: 84, leadership: 92, flair: 94, teamwork: 90 },
    matchLine: 'You believe teams become braver when someone commits fully to an attacking idea.',
    evidence: ['Former New Zealand captain', 'Fastest Test century record', 'Influential attacking coach'],
  },
  {
    name: 'Eoin Morgan',
    country: 'England',
    role: 'Middle-order batter, captain',
    archetype: 'Culture engineer',
    wikipedia: 'https://en.wikipedia.org/wiki/Eoin_Morgan',
    traits: { calm: 88, ambition: 88, risk: 78, creativity: 86, resilience: 84, leadership: 96, flair: 74, teamwork: 94 },
    matchLine: 'You change outcomes by changing the group’s mindset, then trusting people to play freely.',
    evidence: ['Captained England to the 2019 Cricket World Cup', 'Transformed England’s limited-overs approach', 'Left-handed middle-order batter'],
  },
  {
    name: 'Mitchell Starc',
    country: 'Australia',
    role: 'Fast bowler',
    archetype: 'Big-stage strike bowler',
    wikipedia: 'https://en.wikipedia.org/wiki/Mitchell_Starc',
    traits: { calm: 80, ambition: 88, risk: 70, creativity: 66, resilience: 86, leadership: 68, flair: 76, teamwork: 84 },
    matchLine: 'You like making the first decisive move and changing the mood with one clean strike.',
    evidence: ['Left-arm fast bowler', 'World Cup-winning Australia player', 'Known for pace, swing, and yorkers'],
  },
  {
    name: 'Trent Boult',
    country: 'New Zealand',
    role: 'Fast bowler',
    archetype: 'Swing craftsman',
    wikipedia: 'https://en.wikipedia.org/wiki/Trent_Boult',
    traits: { calm: 86, ambition: 84, risk: 56, creativity: 78, resilience: 84, leadership: 66, flair: 70, teamwork: 90 },
    matchLine: 'You win through rhythm, timing, and skill that looks simple only after years of craft.',
    evidence: ['New Zealand left-arm fast bowler', 'World Test Championship winner', 'Known for new-ball swing'],
  },
  {
    name: 'Jos Buttler',
    country: 'England',
    role: 'Wicketkeeper-batter, captain',
    archetype: 'Modern accelerator',
    wikipedia: 'https://en.wikipedia.org/wiki/Jos_Buttler',
    traits: { calm: 78, ambition: 88, risk: 88, creativity: 88, resilience: 82, leadership: 84, flair: 92, teamwork: 84 },
    matchLine: 'You like freedom, fast decisions, and turning a small window into a game-changing burst.',
    evidence: ['England white-ball captain', 'Explosive wicketkeeper-batter', 'World Cup and T20 World Cup winner'],
  },
  {
    name: 'Quinton de Kock',
    country: 'South Africa',
    role: 'Wicketkeeper-batter',
    archetype: 'Free-flowing opener',
    wikipedia: 'https://en.wikipedia.org/wiki/Quinton_de_Kock',
    traits: { calm: 76, ambition: 82, risk: 84, creativity: 78, resilience: 78, leadership: 66, flair: 86, teamwork: 76 },
    matchLine: 'You prefer natural rhythm over overthinking and do your best work when instinct has room.',
    evidence: ['South Africa wicketkeeper-batter', 'Aggressive left-handed opener', 'Successful across international and franchise cricket'],
  },
  {
    name: 'Faf du Plessis',
    country: 'South Africa',
    role: 'Batter, captain',
    archetype: 'Polished competitor',
    wikipedia: 'https://en.wikipedia.org/wiki/Faf_du_Plessis',
    traits: { calm: 86, ambition: 88, risk: 62, creativity: 72, resilience: 90, leadership: 90, flair: 82, teamwork: 86 },
    matchLine: 'You combine discipline, presentation, and competitive edge without losing control.',
    evidence: ['Former South Africa captain', 'Top-order batter', 'Long-running T20 franchise leader'],
  },
  {
    name: 'Dale Steyn',
    country: 'South Africa',
    role: 'Fast bowler',
    archetype: 'Fierce rhythm machine',
    wikipedia: 'https://en.wikipedia.org/wiki/Dale_Steyn',
    traits: { calm: 68, ambition: 94, risk: 78, creativity: 72, resilience: 92, leadership: 72, flair: 88, teamwork: 82 },
    matchLine: 'You thrive on intensity, speed, and the satisfaction of forcing a breakthrough.',
    evidence: ['South Africa fast-bowling great', 'One of the leading Test wicket-takers among pacers', 'Known for pace and outswing'],
  },
  {
    name: 'Moeen Ali',
    country: 'England',
    role: 'All-rounder',
    archetype: 'Easygoing connector',
    wikipedia: 'https://en.wikipedia.org/wiki/Moeen_Ali',
    traits: { calm: 88, ambition: 76, risk: 64, creativity: 78, resilience: 82, leadership: 76, flair: 78, teamwork: 94 },
    matchLine: 'You bring calm, versatility, and trust to groups that need someone to fill the gaps.',
    evidence: ['England spin-bowling all-rounder', 'World Cup and T20 World Cup winner', 'Valuable franchise cricket contributor'],
  },
  {
    name: 'Andre Russell',
    country: 'West Indies',
    role: 'Power all-rounder',
    archetype: 'Impact detonator',
    wikipedia: 'https://en.wikipedia.org/wiki/Andre_Russell',
    traits: { calm: 62, ambition: 86, risk: 96, creativity: 82, resilience: 84, leadership: 66, flair: 99, teamwork: 78 },
    matchLine: 'You are built for short, explosive windows where confidence and power decide everything.',
    evidence: ['T20 power-hitting all-rounder', 'West Indies World T20 winner', 'Long-time franchise match-winner'],
  },
  {
    name: 'Sunil Narine',
    country: 'West Indies',
    role: 'Mystery spin all-rounder',
    archetype: 'Quiet disruptor',
    wikipedia: 'https://en.wikipedia.org/wiki/Sunil_Narine',
    traits: { calm: 88, ambition: 80, risk: 70, creativity: 96, resilience: 84, leadership: 62, flair: 82, teamwork: 82 },
    matchLine: 'You do not need volume to be disruptive; your edge is making familiar things hard to read.',
    evidence: ['Mystery spinner', 'T20 franchise great', 'Reinvented himself as a powerplay batting option'],
  },
  {
    name: 'Tamim Iqbal',
    country: 'Bangladesh',
    role: 'Opening batter',
    archetype: 'Proud trail-setter',
    wikipedia: 'https://en.wikipedia.org/wiki/Tamim_Iqbal',
    traits: { calm: 74, ambition: 88, risk: 74, creativity: 70, resilience: 88, leadership: 82, flair: 76, teamwork: 84 },
    matchLine: 'You like carrying history forward and setting a standard others can build from.',
    evidence: ['Bangladesh opening batter', 'One of Bangladesh’s leading run scorers', 'Former national captain'],
  },
]

export const quizQuestions = [
  {
    prompt: 'A high-pressure day starts badly. What role do you naturally take?',
    options: [
      { label: 'Slow the situation down and rebuild step by step', scores: { calm: 20, resilience: 14, risk: -8 }, roleBoosts: ['top-order', 'batter'], profileBoosts: { 'Rahul Dravid': 16, 'Kane Williamson': 14, 'Joe Root': 14, 'Steve Smith': 12, 'Babar Azam': 12 } },
      { label: 'Act quickly before the problem becomes bigger', scores: { risk: 18, flair: 14, ambition: 10 }, roleBoosts: ['opening', 'batter'], profileBoosts: { 'Virender Sehwag': 16, 'Rishabh Pant': 14, 'Travis Head': 12, 'Brendon McCullum': 12, 'David Warner': 10 } },
      { label: 'Talk through the plan and steady the people around you', scores: { leadership: 18, teamwork: 14, calm: 10 }, profileBoosts: { 'MS Dhoni': 16, 'Kumar Sangakkara': 14, 'Eoin Morgan': 12, 'Faf du Plessis': 12, 'Pat Cummins': 10 } },
      { label: 'Find the one angle everyone else missed', scores: { creativity: 18, calm: 8, risk: 6 }, profileBoosts: { 'AB de Villiers': 14, 'Suryakumar Yadav': 14, 'Glenn Maxwell': 12, 'Sunil Narine': 10, 'Jos Buttler': 10 } },
    ],
  },
  {
    prompt: 'A deadline is close and the margin for error is small. What feels most natural?',
    options: [
      { label: 'Stay calm, sequence the tasks, and finish cleanly', scores: { calm: 20, resilience: 12, leadership: 8 }, roleBoosts: ['finisher', 'keeper'], profileBoosts: { 'MS Dhoni': 18, 'Kane Williamson': 10, 'KL Rahul': 10, 'Michael Bevan': 12 } },
      { label: 'Attack the biggest blocker immediately, even if it is risky', scores: { risk: 20, flair: 16, ambition: 8 }, profileBoosts: { 'Andre Russell': 16, 'Kieron Pollard': 16, 'Yuvraj Singh': 14, 'Hardik Pandya': 14, 'Glenn Maxwell': 12 } },
      { label: 'Keep making small gains until the goal is reachable', scores: { calm: 14, teamwork: 14, resilience: 10 }, profileBoosts: { 'Virat Kohli': 14, 'Joe Root': 12, 'Babar Azam': 10, 'Mahela Jayawardene': 10 } },
      { label: 'Use an unconventional solution if one opening appears', scores: { creativity: 20, flair: 14, risk: 10 }, profileBoosts: { 'AB de Villiers': 18, 'Suryakumar Yadav': 16, 'Rishabh Pant': 12, 'Jos Buttler': 12 } },
    ],
  },
  {
    prompt: 'A project has gone flat and nobody has momentum. How do you change it?',
    options: [
      { label: 'Set a patient structure and let discipline create progress', scores: { calm: 18, leadership: 12, resilience: 10 }, profileBoosts: { 'Anil Kumble': 14, 'Ravichandran Ashwin': 14, 'Pat Cummins': 12, 'Rahul Dravid': 10 } },
      { label: 'Change the angle before everyone accepts the problem', scores: { creativity: 18, leadership: 12, risk: 8 }, profileBoosts: { 'Eoin Morgan': 14, 'MS Dhoni': 12, 'Sunil Narine': 12, 'Shane Warne': 12 } },
      { label: 'Raise the intensity and force a quicker response', scores: { ambition: 16, risk: 12, flair: 8 }, profileBoosts: { 'Dale Steyn': 16, 'Mitchell Starc': 14, 'Shaheen Afridi': 12, 'Waqar Younis': 12 } },
      { label: 'Build a longer trap and let the pattern do the work', scores: { creativity: 18, calm: 14, risk: 2 }, profileBoosts: { 'Shane Warne': 16, 'Muttiah Muralitharan': 16, 'Rashid Khan': 14, 'Ravichandran Ashwin': 12 } },
    ],
  },
  {
    prompt: 'Which powerplay identity fits you best?',
    options: [
      { label: 'Classical opener: judge conditions, then expand', scores: { calm: 18, ambition: 10, risk: -4 }, roleBoosts: ['opening', 'top-order'], profileBoosts: { 'Sachin Tendulkar': 14, 'Rohit Sharma': 14, 'Tamim Iqbal': 12, 'Shubman Gill': 12 } },
      { label: 'Destroyer: make the first six overs feel unfair', scores: { risk: 20, flair: 18, ambition: 8 }, roleBoosts: ['opening'], profileBoosts: { 'Chris Gayle': 18, 'Virender Sehwag': 16, 'David Warner': 14, 'Sanath Jayasuriya': 14, 'Travis Head': 12 } },
      { label: 'Swing bowler: attack stumps before batters adjust', scores: { ambition: 14, resilience: 12, calm: 8 }, roleBoosts: ['bowler', 'fast bowler'], profileBoosts: { 'Wasim Akram': 16, 'Trent Boult': 14, 'Mohammed Shami': 14, 'Bhuvneshwar Kumar': 10, 'Shaheen Afridi': 12 } },
      { label: 'Keeper-reader: spot clues and guide the field', scores: { calm: 14, leadership: 12, teamwork: 10 }, roleBoosts: ['wicketkeeper', 'keeper'], profileBoosts: { 'MS Dhoni': 14, 'Kumar Sangakkara': 14, 'Quinton de Kock': 10, 'KL Rahul': 10 } },
    ],
  },
  {
    prompt: 'A teammate is struggling publicly. What do you do first?',
    options: [
      { label: 'Protect them quietly and simplify their next job', scores: { teamwork: 20, calm: 12, leadership: 8 }, profileBoosts: { 'MS Dhoni': 14, 'Rahul Dravid': 14, 'Kane Williamson': 12, 'Faf du Plessis': 12 } },
      { label: 'Challenge them directly to raise their standard', scores: { ambition: 18, leadership: 14, resilience: 8 }, profileBoosts: { 'Virat Kohli': 16, 'Ricky Ponting': 14, 'Sourav Ganguly': 12, 'Gautam Gambhir': 12 } },
      { label: 'Give them a tactical idea that changes the problem', scores: { creativity: 18, teamwork: 10, calm: 8 }, profileBoosts: { 'Ravichandran Ashwin': 14, 'Eoin Morgan': 12, 'AB de Villiers': 10, 'Sunil Narine': 10 } },
      { label: 'Lift the mood with energy and make the group believe', scores: { flair: 16, teamwork: 14, leadership: 10 }, profileBoosts: { 'Dwayne Bravo': 14, 'Brendon McCullum': 12, 'Shahid Afridi': 12, 'Viv Richards': 10 } },
    ],
  },
  {
    prompt: 'Pick the innings you would be proudest to play.',
    options: [
      { label: 'A fourth-innings Test chase full of judgement and restraint', scores: { calm: 20, resilience: 16, risk: -6 }, profileBoosts: { 'Rahul Dravid': 16, 'Steve Smith': 14, 'Joe Root': 14, 'Kane Williamson': 12 } },
      { label: 'A World Cup knockout hundred when everyone is watching', scores: { ambition: 20, resilience: 10, flair: 8 }, profileBoosts: { 'Ricky Ponting': 14, 'Sachin Tendulkar': 14, 'Virat Kohli': 14, 'Travis Head': 12 } },
      { label: 'A 35-ball T20 hundred that breaks the match open', scores: { flair: 20, risk: 18, ambition: 8 }, profileBoosts: { 'Chris Gayle': 18, 'AB de Villiers': 14, 'Glenn Maxwell': 12, 'Jos Buttler': 12 } },
      { label: 'A gritty 40 not out that gets your team over the line', scores: { teamwork: 18, calm: 14, resilience: 12 }, profileBoosts: { 'MS Dhoni': 14, 'Michael Bevan': 14, 'Ravindra Jadeja': 10, 'KL Rahul': 10 } },
    ],
  },
  {
    prompt: 'What kind of bowler would frustrate you most as a batter?',
    options: [
      { label: 'The yorker specialist who gives no hitting arc', scores: { calm: 16, resilience: 12, creativity: 8 }, profileBoosts: { 'Jasprit Bumrah': 18, 'Lasith Malinga': 16, 'Waqar Younis': 12, 'Dwayne Bravo': 10 } },
      { label: 'The wrist-spinner who hides the ball until it is too late', scores: { creativity: 20, calm: 10, risk: 4 }, profileBoosts: { 'Shane Warne': 18, 'Rashid Khan': 16, 'Yuzvendra Chahal': 10, 'Anil Kumble': 10 } },
      { label: 'The relentless Test seamer who never misses a length', scores: { resilience: 18, calm: 12, ambition: 8 }, profileBoosts: { 'Glenn McGrath': 16, 'Pat Cummins': 14, 'Mohammed Shami': 12, 'Dale Steyn': 12 } },
      { label: 'The left-armer swinging it late at high pace', scores: { ambition: 16, flair: 8, resilience: 10 }, profileBoosts: { 'Wasim Akram': 18, 'Mitchell Starc': 16, 'Shaheen Afridi': 14, 'Trent Boult': 12 } },
    ],
  },
  {
    prompt: 'Your best skill is not working today. What is Plan B?',
    options: [
      { label: 'Strip the game back to basics and survive the spell', scores: { calm: 18, resilience: 16 }, profileBoosts: { 'Rahul Dravid': 14, 'Kane Williamson': 12, 'Babar Azam': 10 } },
      { label: 'Find a different role that still helps the team', scores: { teamwork: 18, creativity: 12, resilience: 10 }, roleBoosts: ['all-rounder'], profileBoosts: { 'Ravindra Jadeja': 14, 'Jacques Kallis': 14, 'Moeen Ali': 12, 'Shakib Al Hasan': 12 } },
      { label: 'Double down and trust the thing that made me dangerous', scores: { ambition: 18, risk: 12, flair: 8 }, profileBoosts: { 'Virat Kohli': 12, 'Viv Richards': 12, 'Andre Russell': 12, 'Dale Steyn': 10 } },
      { label: 'Invent an adjustment before the opposition notices', scores: { creativity: 20, calm: 8, risk: 8 }, profileBoosts: { 'AB de Villiers': 14, 'Ravichandran Ashwin': 14, 'Sunil Narine': 12, 'Glenn Maxwell': 12 } },
    ],
  },
  {
    prompt: 'Which leadership style feels most honest to you?',
    options: [
      { label: 'Minimal words, maximum clarity in tense moments', scores: { calm: 20, leadership: 16 }, profileBoosts: { 'MS Dhoni': 18, 'Kane Williamson': 14, 'Mahela Jayawardene': 12 } },
      { label: 'Visible intensity that raises everyone’s standards', scores: { ambition: 20, leadership: 16, resilience: 8 }, profileBoosts: { 'Virat Kohli': 18, 'Ricky Ponting': 16, 'Sourav Ganguly': 14, 'Pat Cummins': 10 } },
      { label: 'Tactical empathy: understand people and matchups', scores: { teamwork: 18, creativity: 12, leadership: 12 }, profileBoosts: { 'Eoin Morgan': 16, 'Kumar Sangakkara': 14, 'Faf du Plessis': 12, 'Rahul Dravid': 10 } },
      { label: 'Lead through skill so undeniable that others follow', scores: { ambition: 18, flair: 10, resilience: 10 }, profileBoosts: { 'Sachin Tendulkar': 14, 'Brian Lara': 14, 'Wasim Akram': 12, 'Muttiah Muralitharan': 12 } },
    ],
  },
  {
    prompt: 'A pitch is slow and gripping. What do you trust?',
    options: [
      { label: 'Soft hands, late cuts, and low-risk rotation', scores: { calm: 18, creativity: 8, risk: -4 }, profileBoosts: { 'Joe Root': 12, 'Kane Williamson': 12, 'Babar Azam': 10, 'Mahela Jayawardene': 10 } },
      { label: 'Sweep options and weird angles to break the field', scores: { creativity: 20, flair: 14, risk: 8 }, profileBoosts: { 'AB de Villiers': 14, 'Suryakumar Yadav': 14, 'Glenn Maxwell': 12, 'Rishabh Pant': 12 } },
      { label: 'Hit spin hard before it starts dictating terms', scores: { risk: 18, flair: 12, ambition: 8 }, profileBoosts: { 'Yuvraj Singh': 14, 'Shahid Afridi': 12, 'Chris Gayle': 12, 'David Warner': 10 } },
      { label: 'Bowl cutters, into-the-pitch lengths, and force errors', scores: { calm: 14, creativity: 14, resilience: 8 }, roleBoosts: ['bowler'], profileBoosts: { 'Dwayne Bravo': 14, 'Jasprit Bumrah': 12, 'Sunil Narine': 12, 'Ravichandran Ashwin': 12 } },
    ],
  },
  {
    prompt: 'Which fielding moment sounds most like you?',
    options: [
      { label: 'A direct hit because you read the single early', scores: { calm: 14, creativity: 8, teamwork: 10 }, profileBoosts: { 'Ravindra Jadeja': 16, 'AB de Villiers': 12, 'MS Dhoni': 10 } },
      { label: 'A boundary catch that needs athletic risk', scores: { flair: 16, risk: 12, resilience: 8 }, profileBoosts: { 'Kieron Pollard': 14, 'Glenn Maxwell': 12, 'Ben Stokes': 12, 'Ravindra Jadeja': 10 } },
      { label: 'Keeping calm when the ball is turning sharply', scores: { calm: 18, teamwork: 10, leadership: 8 }, roleBoosts: ['keeper', 'wicketkeeper'], profileBoosts: { 'MS Dhoni': 14, 'Kumar Sangakkara': 14, 'Rishabh Pant': 10, 'Quinton de Kock': 10 } },
      { label: 'Saving ten runs through repeat effort, not one highlight', scores: { teamwork: 18, resilience: 12, calm: 6 }, profileBoosts: { 'Rahul Dravid': 10, 'Faf du Plessis': 12, 'Pat Cummins': 10, 'Ravindra Jadeja': 10 } },
    ],
  },
  {
    prompt: 'What type of comeback story fits you?',
    options: [
      { label: 'A long technical rebuild that few people notice at first', scores: { resilience: 20, calm: 14, ambition: 8 }, profileBoosts: { 'Steve Smith': 14, 'Joe Root': 12, 'Ajinkya Rahane': 12, 'Rahul Dravid': 10 } },
      { label: 'A public setback turned into fuel', scores: { resilience: 18, ambition: 16, leadership: 6 }, profileBoosts: { 'Virat Kohli': 14, 'Yash Dayal': 12, 'Sourav Ganguly': 12, 'Rishabh Pant': 12 } },
      { label: 'Reinventing your role so the team needs you again', scores: { creativity: 18, teamwork: 12, resilience: 12 }, profileBoosts: { 'Sunil Narine': 16, 'Ravindra Jadeja': 12, 'Moeen Ali': 10, 'Shivam Dube': 10 } },
      { label: 'Coming back faster, louder, and more fearless', scores: { flair: 16, risk: 12, resilience: 14 }, profileBoosts: { 'Rishabh Pant': 14, 'Shahid Afridi': 12, 'Andre Russell': 12, 'Hardik Pandya': 12 } },
    ],
  },
  {
    prompt: 'If you were picked in a cricket XI, which job would feel most natural?',
    options: [
      { label: 'Top-order batter who sets the innings', scores: { calm: 12, ambition: 12, risk: 2 }, roleBoosts: ['batter', 'opening', 'top-order'], profileBoosts: { 'Rohit Sharma': 10, 'Shubman Gill': 10, 'Babar Azam': 10, 'Sachin Tendulkar': 10 } },
      { label: 'Wicketkeeper or finisher who reads the finish', scores: { calm: 16, leadership: 8, teamwork: 8 }, roleBoosts: ['wicketkeeper', 'finisher', 'keeper'], profileBoosts: { 'MS Dhoni': 14, 'Kumar Sangakkara': 12, 'Rishabh Pant': 10, 'KL Rahul': 10 } },
      { label: 'All-rounder who changes the balance of the side', scores: { teamwork: 16, resilience: 10, creativity: 8 }, roleBoosts: ['all-rounder', 'all-rounder, captain'], profileBoosts: { 'Jacques Kallis': 14, 'Ravindra Jadeja': 14, 'Hardik Pandya': 12, 'Ben Stokes': 12 } },
      { label: 'Bowler who takes responsibility when runs are tight', scores: { calm: 14, resilience: 12, creativity: 6 }, roleBoosts: ['bowler', 'spinner', 'fast bowler'], profileBoosts: { 'Jasprit Bumrah': 14, 'Rashid Khan': 12, 'Mitchell Starc': 12, 'Mohammed Shami': 10 } },
    ],
  },
  {
    prompt: 'Which batting style feels closest to your personality?',
    options: [
      { label: 'Patient accumulation until the game bends', scores: { calm: 20, risk: -8, resilience: 12 }, roleBoosts: ['top-order'], profileBoosts: { 'Rahul Dravid': 16, 'Joe Root': 14, 'Kane Williamson': 14, 'Babar Azam': 12, 'Tamim Iqbal': 12 } },
      { label: 'Explosive opening that changes the first ten minutes', scores: { risk: 20, flair: 16, ambition: 8 }, roleBoosts: ['opening'], profileBoosts: { 'Virender Sehwag': 16, 'Chris Gayle': 16, 'David Warner': 14, 'Sanath Jayasuriya': 12, 'Brendon McCullum': 12 } },
      { label: 'Inventive shots and angles no one can set fields for', scores: { creativity: 22, flair: 16, risk: 10 }, profileBoosts: { 'AB de Villiers': 16, 'Suryakumar Yadav': 16, 'Glenn Maxwell': 12, 'Rishabh Pant': 12, 'Jos Buttler': 10 } },
      { label: 'Late-overs power with the match on one swing', scores: { risk: 18, flair: 14, resilience: 10 }, profileBoosts: { 'MS Dhoni': 12, 'Yuvraj Singh': 14, 'Andre Russell': 16, 'Kieron Pollard': 16, 'Dwayne Bravo': 10, 'Hardik Pandya': 12 } },
    ],
  },
  {
    prompt: 'If the match is decided by bowling, what kind of threat are you?',
    options: [
      { label: 'New-ball swing and seam at full intensity', scores: { ambition: 14, resilience: 12, calm: 8 }, profileBoosts: { 'Wasim Akram': 16, 'Waqar Younis': 14, 'Dale Steyn': 14, 'Shaheen Afridi': 12, 'Trent Boult': 12, 'Mitchell Starc': 12, 'Mohammed Shami': 10 } },
      { label: 'Death-overs precision when one ball matters', scores: { calm: 20, resilience: 12, creativity: 8 }, profileBoosts: { 'Jasprit Bumrah': 18, 'Lasith Malinga': 18, 'Sunil Narine': 10, 'Dwayne Bravo': 12 } },
      { label: 'Spin, mystery, and traps that get smarter every over', scores: { creativity: 22, calm: 10, risk: 4 }, profileBoosts: { 'Shane Warne': 18, 'Muttiah Muralitharan': 18, 'Ravichandran Ashwin': 14, 'Anil Kumble': 12, 'Rashid Khan': 14, 'Sunil Narine': 10 } },
      { label: 'I would rather win it with batting or leadership', scores: { leadership: 12, teamwork: 10, ambition: 8 }, profileBoosts: { 'Ricky Ponting': 12, 'Sourav Ganguly': 12, 'Eoin Morgan': 12, 'Faf du Plessis': 10, 'Kumar Sangakkara': 10 } },
    ],
  },
  {
    prompt: 'What matters most when you watch cricket?',
    options: [
      { label: 'Technical excellence that stands up across formats', scores: { ambition: 16, calm: 12, resilience: 10 }, profileBoosts: { 'Sachin Tendulkar': 16, 'Virat Kohli': 14, 'Steve Smith': 14, 'Joe Root': 12 } },
      { label: 'Moments that make a stadium explode', scores: { flair: 20, risk: 14, creativity: 8 }, profileBoosts: { 'Chris Gayle': 16, 'Yuvraj Singh': 14, 'Shahid Afridi': 14, 'AB de Villiers': 12 } },
      { label: 'Tactical layers: matchups, fields, and pressure', scores: { creativity: 18, calm: 12, leadership: 10 }, profileBoosts: { 'Ravichandran Ashwin': 16, 'Eoin Morgan': 14, 'MS Dhoni': 12, 'Shane Warne': 12 } },
      { label: 'Team culture and players who make others better', scores: { teamwork: 20, leadership: 14, calm: 6 }, profileBoosts: { 'Rahul Dravid': 14, 'Faf du Plessis': 12, 'Pat Cummins': 12, 'Kane Williamson': 12 } },
    ],
  },
  {
    prompt: 'A batter is dominating you. What is your next ball?',
    options: [
      { label: 'The same hard length, because discipline will win later', scores: { calm: 18, resilience: 16 }, profileBoosts: { 'Glenn McGrath': 16, 'Pat Cummins': 14, 'Mohammed Shami': 12 } },
      { label: 'A slower ball or cutter that changes the pace completely', scores: { creativity: 18, calm: 8, risk: 8 }, profileBoosts: { 'Dwayne Bravo': 16, 'Jasprit Bumrah': 12, 'Harshal Patel': 10, 'Sunil Narine': 10 } },
      { label: 'A bouncer/yorker statement ball to reclaim space', scores: { ambition: 18, risk: 14, flair: 8 }, profileBoosts: { 'Dale Steyn': 14, 'Mitchell Starc': 14, 'Waqar Younis': 12, 'Lasith Malinga': 12 } },
      { label: 'Set a trap with the field and make them hit to it', scores: { creativity: 20, leadership: 8, calm: 10 }, profileBoosts: { 'Shane Warne': 16, 'Ravichandran Ashwin': 16, 'Anil Kumble': 12, 'Rashid Khan': 12 } },
    ],
  },
  {
    prompt: 'Which batting weakness would you rather spend months fixing?',
    options: [
      { label: 'Leaving and defending better outside off stump', scores: { calm: 18, resilience: 16, ambition: 8 }, profileBoosts: { 'Rahul Dravid': 16, 'Steve Smith': 14, 'Joe Root': 12, 'Kane Williamson': 12 } },
      { label: 'Power-hitting against pace at the death', scores: { ambition: 16, risk: 12, flair: 12 }, profileBoosts: { 'Hardik Pandya': 14, 'Andre Russell': 14, 'Kieron Pollard': 12, 'Yuvraj Singh': 12 } },
      { label: 'Expanding range against spin without losing control', scores: { creativity: 18, calm: 10, risk: 8 }, profileBoosts: { 'AB de Villiers': 14, 'Suryakumar Yadav': 14, 'Rishabh Pant': 12, 'Glenn Maxwell': 12 } },
      { label: 'Converting starts into big hundreds', scores: { ambition: 20, resilience: 12, calm: 8 }, profileBoosts: { 'Virat Kohli': 16, 'Sachin Tendulkar': 14, 'Rohit Sharma': 14, 'Shubman Gill': 12 } },
    ],
  },
  {
    prompt: 'Which trophy path feels most meaningful?',
    options: [
      { label: 'A long league season where consistency wins', scores: { resilience: 18, calm: 12, teamwork: 10 }, profileBoosts: { 'Rohit Sharma': 14, 'MS Dhoni': 14, 'Faf du Plessis': 10, 'Kane Williamson': 10 } },
      { label: 'A World Cup final where one performance defines history', scores: { ambition: 20, flair: 10, resilience: 10 }, profileBoosts: { 'Ricky Ponting': 14, 'Travis Head': 14, 'Kapil Dev': 12, 'Ben Stokes': 12 } },
      { label: 'A comeback title after years of doubt', scores: { resilience: 20, leadership: 10, teamwork: 8 }, profileBoosts: { 'Virat Kohli': 14, 'Ravindra Jadeja': 10, 'Ajinkya Rahane': 10, 'Sourav Ganguly': 10 } },
      { label: 'A title won by changing how the format is played', scores: { creativity: 18, risk: 12, flair: 8 }, profileBoosts: { 'Brendon McCullum': 14, 'Eoin Morgan': 14, 'Sunil Narine': 12, 'Shane Warne': 12 } },
    ],
  },
  {
    prompt: 'How do you prefer to handle pressure from fans and media?',
    options: [
      { label: 'Keep the outside noise out and stay process-driven', scores: { calm: 20, resilience: 12 }, profileBoosts: { 'Kane Williamson': 14, 'Rahul Dravid': 14, 'Joe Root': 12, 'Pat Cummins': 10 } },
      { label: 'Use it as competitive oxygen', scores: { ambition: 20, flair: 8, resilience: 10 }, profileBoosts: { 'Virat Kohli': 18, 'Viv Richards': 14, 'Ricky Ponting': 12, 'Dale Steyn': 10 } },
      { label: 'Answer with one unforgettable performance', scores: { flair: 18, risk: 12, ambition: 10 }, profileBoosts: { 'Brian Lara': 14, 'Chris Gayle': 14, 'Rishabh Pant': 12, 'Shahid Afridi': 12 } },
      { label: 'Make sure the team feels protected first', scores: { teamwork: 18, leadership: 14, calm: 8 }, profileBoosts: { 'MS Dhoni': 14, 'Eoin Morgan': 12, 'Kumar Sangakkara': 12, 'Faf du Plessis': 10 } },
    ],
  },
  {
    prompt: 'What kind of player would you trust in a super over?',
    options: [
      { label: 'A yorker bowler who can repeat the skill under chaos', scores: { calm: 20, resilience: 14 }, roleBoosts: ['bowler'], profileBoosts: { 'Jasprit Bumrah': 18, 'Lasith Malinga': 16, 'Mitchell Starc': 10 } },
      { label: 'A batter with 360-degree access to every field setting', scores: { creativity: 20, flair: 16, risk: 10 }, profileBoosts: { 'AB de Villiers': 18, 'Suryakumar Yadav': 16, 'Glenn Maxwell': 12 } },
      { label: 'A finisher who stays cold when the crowd gets loud', scores: { calm: 18, leadership: 10, resilience: 12 }, profileBoosts: { 'MS Dhoni': 18, 'Michael Bevan': 12, 'Hardik Pandya': 10 } },
      { label: 'A fearless striker who can end it in two balls', scores: { risk: 20, flair: 18, ambition: 8 }, profileBoosts: { 'Andre Russell': 18, 'Chris Gayle': 14, 'Kieron Pollard': 14, 'Yuvraj Singh': 12 } },
    ],
  },
  {
    prompt: 'Which cricket legacy sounds most like the story you would want?',
    options: [
      { label: 'The standard-setter everyone measures themselves against', scores: { ambition: 20, resilience: 12, risk: -4 }, profileBoosts: { 'Sachin Tendulkar': 18, 'Virat Kohli': 18, 'Steve Smith': 14, 'Brian Lara': 12, 'Viv Richards': 12 } },
      { label: 'The captain who changed how a team believed', scores: { leadership: 22, teamwork: 14, calm: 8 }, profileBoosts: { 'MS Dhoni': 18, 'Kapil Dev': 12, 'Ricky Ponting': 12, 'Eoin Morgan': 12, 'Sourav Ganguly': 12, 'Pat Cummins': 10 } },
      { label: 'The all-round problem solver who is always useful', scores: { teamwork: 20, resilience: 12, creativity: 8 }, profileBoosts: { 'Jacques Kallis': 18, 'Ravindra Jadeja': 14, 'Shakib Al Hasan': 14, 'Moeen Ali': 12, 'Ben Stokes': 12, 'Kapil Dev': 10 } },
      { label: 'The entertainer people remember because the game felt alive', scores: { flair: 22, risk: 16, creativity: 10 }, profileBoosts: { 'Shahid Afridi': 14, 'Chris Gayle': 14, 'Glenn Maxwell': 12, 'AB de Villiers': 12, 'Quinton de Kock': 10, 'Jos Buttler': 10 } },
    ],
  },
  {
    prompt: 'What kind of practice session would you choose before a final?',
    options: [
      { label: 'Long technical repetitions until every movement feels stable', scores: { calm: 18, resilience: 14, ambition: 8 }, profileBoosts: { 'Rahul Dravid': 16, 'Sachin Tendulkar': 14, 'Kane Williamson': 12, 'Joe Root': 12 } },
      { label: 'Scenario training: last over, hostile crowd, no easy singles', scores: { calm: 16, leadership: 10, resilience: 12 }, profileBoosts: { 'MS Dhoni': 16, 'Jasprit Bumrah': 14, 'Lasith Malinga': 12, 'Michael Bevan': 12 } },
      { label: 'Power and range-hitting until the field feels irrelevant', scores: { flair: 18, risk: 14, ambition: 10 }, profileBoosts: { 'Chris Gayle': 14, 'Andre Russell': 14, 'Kieron Pollard': 12, 'Yuvraj Singh': 12, 'Glenn Maxwell': 12 } },
      { label: 'Matchup lab: plans for every batter, bowler, and field', scores: { creativity: 18, teamwork: 10, leadership: 8 }, profileBoosts: { 'Ravichandran Ashwin': 16, 'Eoin Morgan': 14, 'Sunil Narine': 12, 'Shane Warne': 12 } },
    ],
  },
  {
    prompt: 'Which mistake would bother you most after a loss?',
    options: [
      { label: 'Losing shape under pressure when calm judgement was needed', scores: { calm: 18, resilience: 10, leadership: 6 }, profileBoosts: { 'Kane Williamson': 14, 'MS Dhoni': 14, 'Rahul Dravid': 12, 'Pat Cummins': 10 } },
      { label: 'Failing to take the aggressive option when the game asked for it', scores: { ambition: 18, risk: 12, flair: 8 }, profileBoosts: { 'Virat Kohli': 14, 'Viv Richards': 14, 'Ricky Ponting': 12, 'Dale Steyn': 10 } },
      { label: 'Missing the clever adjustment that could have changed the matchup', scores: { creativity: 20, calm: 8, teamwork: 6 }, profileBoosts: { 'AB de Villiers': 12, 'Ravichandran Ashwin': 16, 'Suryakumar Yadav': 12, 'Sunil Narine': 12 } },
      { label: 'Letting the team drift instead of pulling everyone together', scores: { teamwork: 20, leadership: 14, resilience: 6 }, profileBoosts: { 'Faf du Plessis': 14, 'Kumar Sangakkara': 14, 'Sourav Ganguly': 12, 'Eoin Morgan': 12 } },
    ],
  },
  {
    prompt: 'Pick the cricket lane that feels most like your inner game.',
    options: [
      { label: 'Calm captain and composed keeper energy', scores: { calm: 18, leadership: 16, teamwork: 10 }, profileBoosts: { 'MS Dhoni': 55, 'Kane Williamson': 55, 'Kumar Sangakkara': 55, 'Mahela Jayawardene': 55, 'Faf du Plessis': 55 } },
      { label: 'Intense standard-setter who lifts the room', scores: { ambition: 20, leadership: 14, resilience: 10 }, profileBoosts: { 'Virat Kohli': 55, 'Ricky Ponting': 55, 'Sourav Ganguly': 55, 'Gautam Gambhir': 55, 'Pat Cummins': 55 } },
      { label: 'Classic batting master with endless patience', scores: { calm: 18, ambition: 14, risk: -10 }, profileBoosts: { 'Sachin Tendulkar': 55, 'Rahul Dravid': 55, 'Joe Root': 55, 'Steve Smith': 55, 'Babar Azam': 55 } },
      { label: 'Explosive opener who owns the first move', scores: { risk: 20, flair: 16, ambition: 8 }, profileBoosts: { 'Rohit Sharma': 55, 'Virender Sehwag': 55, 'Chris Gayle': 55, 'David Warner': 55, 'Sanath Jayasuriya': 55 } },
      { label: 'Inventive batter who sees impossible angles', scores: { creativity: 22, flair: 18, risk: 12 }, profileBoosts: { 'AB de Villiers': 55, 'Suryakumar Yadav': 55, 'Glenn Maxwell': 55, 'Rishabh Pant': 55, 'Jos Buttler': 55 } },
      { label: 'Late-over power and fearless finishing', scores: { risk: 20, flair: 18, resilience: 10 }, profileBoosts: { 'Yuvraj Singh': 55, 'Hardik Pandya': 55, 'Andre Russell': 55, 'Kieron Pollard': 55, 'Dwayne Bravo': 55 } },
      { label: 'Seam craft, swing, and pressure control', scores: { calm: 16, resilience: 14, creativity: 8 }, profileBoosts: { 'Jasprit Bumrah': 55, 'Mohammed Shami': 55, 'Wasim Akram': 55, 'Waqar Younis': 55, 'Trent Boult': 55 } },
      { label: 'Raw pace, yorkers, and intimidation', scores: { ambition: 16, resilience: 14, flair: 8 }, profileBoosts: { 'Dale Steyn': 55, 'Mitchell Starc': 55, 'Shaheen Afridi': 55, 'Lasith Malinga': 55, 'Jasprit Bumrah': 35 } },
      { label: 'Spin, mystery, and tactical traps', scores: { creativity: 22, calm: 12, risk: 4 }, profileBoosts: { 'Ravichandran Ashwin': 55, 'Anil Kumble': 55, 'Shane Warne': 55, 'Muttiah Muralitharan': 55, 'Rashid Khan': 55 } },
      { label: 'All-round balance and useful in every phase', scores: { teamwork: 20, resilience: 14, creativity: 8 }, profileBoosts: { 'Kapil Dev': 55, 'Ravindra Jadeja': 55, 'Jacques Kallis': 55, 'Shakib Al Hasan': 55, 'Moeen Ali': 55, 'Ben Stokes': 55 } },
      { label: 'Fearless icon who makes the game feel bigger', scores: { flair: 22, risk: 18, creativity: 10 }, profileBoosts: { 'Viv Richards': 55, 'Brian Lara': 55, 'Shahid Afridi': 55, 'Brendon McCullum': 55, 'Quinton de Kock': 55 } },
      { label: 'Adaptable modern thinker with tactical range', scores: { calm: 12, creativity: 14, teamwork: 14 }, profileBoosts: { 'Sunil Narine': 55, 'Eoin Morgan': 55, 'Tamim Iqbal': 55, 'KL Rahul': 55, 'Shubman Gill': 55 } },
    ],
  },
]
